//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arconfirmationletter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TRUONG\\SQLEXPRESS;Initial Catalog=ARconfirmationletter;Persist Securi" +
            "ty Info=True;User ID=sql;Password=Tienmat1$")]
        public string ARconfirmationletterConnectionString {
            get {
                return ((string)(this["ARconfirmationletterConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-8D4F853\\SQLEXPRESS;Initial Catalog=ARconfirmationletter;Persi" +
            "st Security Info=True;User ID=sa;Password=123123")]
        public string ARconfirmationletterConnectionString1 {
            get {
                return ((string)(this["ARconfirmationletterConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-8D4F853\\SQLEXPRESS;Initial Catalog=KAmanagement;Persist Secur" +
            "ity Info=True;User ID=sa;Password=123123")]
        public string KAmanagementConnectionString {
            get {
                return ((string)(this["KAmanagementConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-Q6VJ0TS\\SQLEXPRESS;Initial Catalog=ARconfirmationletter;Persi" +
            "st Security Info=True;User ID=sa;Password=123123")]
        public string ARconfirmationletterConnectionString2 {
            get {
                return ((string)(this["ARconfirmationletterConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HAN-L-3PFF7H2;Initial Catalog=ARconfirmationletter;Persist Security I" +
            "nfo=True;User ID=sa;Password=tienmat1$")]
        public string ARconfirmationletterConnectionString3 {
            get {
                return ((string)(this["ARconfirmationletterConnectionString3"]));
            }
        }
    }
}
