#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arconfirmationletter
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Luckynumber")]
	public partial class LinqtoSQLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Temp(tbl_Temp instance);
    partial void Updatetbl_Temp(tbl_Temp instance);
    partial void Deletetbl_Temp(tbl_Temp instance);
    #endregion
		
		public LinqtoSQLDataContext() : 
				base(global::arconfirmationletter.Properties.Settings.Default.LuckynumberConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqtoSQLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqtoSQLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqtoSQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqtoSQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Temp> tbl_Temps
		{
			get
			{
				return this.GetTable<tbl_Temp>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Temp")]
	public partial class tbl_Temp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _Version;
		
		private string _server;
		
		private string _username;
		
		private string _password;
		
		private string _signoffby;
		
		private string _possition;
		
		private string _phonecontact;
		
		private System.Nullable<int> _siteid;
		
		private string _note;
		
		private string _contactperson;
		
		private string _nameofbarnch;
		
		private string _addressofbarnch;
		
		private bool _DeleteData;
		
		private bool _EditServerData;
		
		private bool _Depositintput;
		
		private bool _EditReportsaffter;
		
		private bool _InputDepositInpass;
		
		private bool _PriodMake;
		
		private bool _Systemconfig;
		
		private bool _uploadBeginbalance;
		
		private bool _endyearPackdata;
		
		private bool _makedepostfromadjamount;
		
		private bool _deductdepositamount;
		
		private bool _redoInputviry;
		
		private bool _uploadpriviousPriod;
		
		private System.Data.Linq.Binary _imagesign;
		
		private bool _nationKA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnVersionChanging(System.Nullable<int> value);
    partial void OnVersionChanged();
    partial void OnserverChanging(string value);
    partial void OnserverChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnsignoffbyChanging(string value);
    partial void OnsignoffbyChanged();
    partial void OnpossitionChanging(string value);
    partial void OnpossitionChanged();
    partial void OnphonecontactChanging(string value);
    partial void OnphonecontactChanged();
    partial void OnsiteidChanging(System.Nullable<int> value);
    partial void OnsiteidChanged();
    partial void OnnoteChanging(string value);
    partial void OnnoteChanged();
    partial void OncontactpersonChanging(string value);
    partial void OncontactpersonChanged();
    partial void OnnameofbarnchChanging(string value);
    partial void OnnameofbarnchChanged();
    partial void OnaddressofbarnchChanging(string value);
    partial void OnaddressofbarnchChanged();
    partial void OnDeleteDataChanging(bool value);
    partial void OnDeleteDataChanged();
    partial void OnEditServerDataChanging(bool value);
    partial void OnEditServerDataChanged();
    partial void OnDepositintputChanging(bool value);
    partial void OnDepositintputChanged();
    partial void OnEditReportsaffterChanging(bool value);
    partial void OnEditReportsaffterChanged();
    partial void OnInputDepositInpassChanging(bool value);
    partial void OnInputDepositInpassChanged();
    partial void OnPriodMakeChanging(bool value);
    partial void OnPriodMakeChanged();
    partial void OnSystemconfigChanging(bool value);
    partial void OnSystemconfigChanged();
    partial void OnuploadBeginbalanceChanging(bool value);
    partial void OnuploadBeginbalanceChanged();
    partial void OnendyearPackdataChanging(bool value);
    partial void OnendyearPackdataChanged();
    partial void OnmakedepostfromadjamountChanging(bool value);
    partial void OnmakedepostfromadjamountChanged();
    partial void OndeductdepositamountChanging(bool value);
    partial void OndeductdepositamountChanged();
    partial void OnredoInputviryChanging(bool value);
    partial void OnredoInputviryChanged();
    partial void OnuploadpriviousPriodChanging(bool value);
    partial void OnuploadpriviousPriodChanged();
    partial void OnimagesignChanging(System.Data.Linq.Binary value);
    partial void OnimagesignChanged();
    partial void OnnationKAChanging(bool value);
    partial void OnnationKAChanged();
    #endregion
		
		public tbl_Temp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="Int")]
		public System.Nullable<int> Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this.OnVersionChanging(value);
					this.SendPropertyChanging();
					this._Version = value;
					this.SendPropertyChanged("Version");
					this.OnVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_server", DbType="NChar(225)")]
		public string server
		{
			get
			{
				return this._server;
			}
			set
			{
				if ((this._server != value))
				{
					this.OnserverChanging(value);
					this.SendPropertyChanging();
					this._server = value;
					this.SendPropertyChanged("server");
					this.OnserverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NChar(225)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NChar(225)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_signoffby", DbType="NChar(225)")]
		public string signoffby
		{
			get
			{
				return this._signoffby;
			}
			set
			{
				if ((this._signoffby != value))
				{
					this.OnsignoffbyChanging(value);
					this.SendPropertyChanging();
					this._signoffby = value;
					this.SendPropertyChanged("signoffby");
					this.OnsignoffbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_possition", DbType="NChar(225)")]
		public string possition
		{
			get
			{
				return this._possition;
			}
			set
			{
				if ((this._possition != value))
				{
					this.OnpossitionChanging(value);
					this.SendPropertyChanging();
					this._possition = value;
					this.SendPropertyChanged("possition");
					this.OnpossitionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phonecontact", DbType="NChar(225)")]
		public string phonecontact
		{
			get
			{
				return this._phonecontact;
			}
			set
			{
				if ((this._phonecontact != value))
				{
					this.OnphonecontactChanging(value);
					this.SendPropertyChanging();
					this._phonecontact = value;
					this.SendPropertyChanged("phonecontact");
					this.OnphonecontactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteid", DbType="Int")]
		public System.Nullable<int> siteid
		{
			get
			{
				return this._siteid;
			}
			set
			{
				if ((this._siteid != value))
				{
					this.OnsiteidChanging(value);
					this.SendPropertyChanging();
					this._siteid = value;
					this.SendPropertyChanged("siteid");
					this.OnsiteidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_note", DbType="NChar(225)")]
		public string note
		{
			get
			{
				return this._note;
			}
			set
			{
				if ((this._note != value))
				{
					this.OnnoteChanging(value);
					this.SendPropertyChanging();
					this._note = value;
					this.SendPropertyChanged("note");
					this.OnnoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactperson", DbType="NChar(225)")]
		public string contactperson
		{
			get
			{
				return this._contactperson;
			}
			set
			{
				if ((this._contactperson != value))
				{
					this.OncontactpersonChanging(value);
					this.SendPropertyChanging();
					this._contactperson = value;
					this.SendPropertyChanged("contactperson");
					this.OncontactpersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameofbarnch", DbType="NChar(225)")]
		public string nameofbarnch
		{
			get
			{
				return this._nameofbarnch;
			}
			set
			{
				if ((this._nameofbarnch != value))
				{
					this.OnnameofbarnchChanging(value);
					this.SendPropertyChanging();
					this._nameofbarnch = value;
					this.SendPropertyChanged("nameofbarnch");
					this.OnnameofbarnchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addressofbarnch", DbType="NChar(225)")]
		public string addressofbarnch
		{
			get
			{
				return this._addressofbarnch;
			}
			set
			{
				if ((this._addressofbarnch != value))
				{
					this.OnaddressofbarnchChanging(value);
					this.SendPropertyChanging();
					this._addressofbarnch = value;
					this.SendPropertyChanged("addressofbarnch");
					this.OnaddressofbarnchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteData", DbType="Bit NOT NULL")]
		public bool DeleteData
		{
			get
			{
				return this._DeleteData;
			}
			set
			{
				if ((this._DeleteData != value))
				{
					this.OnDeleteDataChanging(value);
					this.SendPropertyChanging();
					this._DeleteData = value;
					this.SendPropertyChanged("DeleteData");
					this.OnDeleteDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditServerData", DbType="Bit NOT NULL")]
		public bool EditServerData
		{
			get
			{
				return this._EditServerData;
			}
			set
			{
				if ((this._EditServerData != value))
				{
					this.OnEditServerDataChanging(value);
					this.SendPropertyChanging();
					this._EditServerData = value;
					this.SendPropertyChanged("EditServerData");
					this.OnEditServerDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Depositintput", DbType="Bit NOT NULL")]
		public bool Depositintput
		{
			get
			{
				return this._Depositintput;
			}
			set
			{
				if ((this._Depositintput != value))
				{
					this.OnDepositintputChanging(value);
					this.SendPropertyChanging();
					this._Depositintput = value;
					this.SendPropertyChanged("Depositintput");
					this.OnDepositintputChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditReportsaffter", DbType="Bit NOT NULL")]
		public bool EditReportsaffter
		{
			get
			{
				return this._EditReportsaffter;
			}
			set
			{
				if ((this._EditReportsaffter != value))
				{
					this.OnEditReportsaffterChanging(value);
					this.SendPropertyChanging();
					this._EditReportsaffter = value;
					this.SendPropertyChanged("EditReportsaffter");
					this.OnEditReportsaffterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InputDepositInpass", DbType="Bit NOT NULL")]
		public bool InputDepositInpass
		{
			get
			{
				return this._InputDepositInpass;
			}
			set
			{
				if ((this._InputDepositInpass != value))
				{
					this.OnInputDepositInpassChanging(value);
					this.SendPropertyChanging();
					this._InputDepositInpass = value;
					this.SendPropertyChanged("InputDepositInpass");
					this.OnInputDepositInpassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriodMake", DbType="Bit NOT NULL")]
		public bool PriodMake
		{
			get
			{
				return this._PriodMake;
			}
			set
			{
				if ((this._PriodMake != value))
				{
					this.OnPriodMakeChanging(value);
					this.SendPropertyChanging();
					this._PriodMake = value;
					this.SendPropertyChanged("PriodMake");
					this.OnPriodMakeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Systemconfig", DbType="Bit NOT NULL")]
		public bool Systemconfig
		{
			get
			{
				return this._Systemconfig;
			}
			set
			{
				if ((this._Systemconfig != value))
				{
					this.OnSystemconfigChanging(value);
					this.SendPropertyChanging();
					this._Systemconfig = value;
					this.SendPropertyChanged("Systemconfig");
					this.OnSystemconfigChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uploadBeginbalance", DbType="Bit NOT NULL")]
		public bool uploadBeginbalance
		{
			get
			{
				return this._uploadBeginbalance;
			}
			set
			{
				if ((this._uploadBeginbalance != value))
				{
					this.OnuploadBeginbalanceChanging(value);
					this.SendPropertyChanging();
					this._uploadBeginbalance = value;
					this.SendPropertyChanged("uploadBeginbalance");
					this.OnuploadBeginbalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endyearPackdata", DbType="Bit NOT NULL")]
		public bool endyearPackdata
		{
			get
			{
				return this._endyearPackdata;
			}
			set
			{
				if ((this._endyearPackdata != value))
				{
					this.OnendyearPackdataChanging(value);
					this.SendPropertyChanging();
					this._endyearPackdata = value;
					this.SendPropertyChanged("endyearPackdata");
					this.OnendyearPackdataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makedepostfromadjamount", DbType="Bit NOT NULL")]
		public bool makedepostfromadjamount
		{
			get
			{
				return this._makedepostfromadjamount;
			}
			set
			{
				if ((this._makedepostfromadjamount != value))
				{
					this.OnmakedepostfromadjamountChanging(value);
					this.SendPropertyChanging();
					this._makedepostfromadjamount = value;
					this.SendPropertyChanged("makedepostfromadjamount");
					this.OnmakedepostfromadjamountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deductdepositamount", DbType="Bit NOT NULL")]
		public bool deductdepositamount
		{
			get
			{
				return this._deductdepositamount;
			}
			set
			{
				if ((this._deductdepositamount != value))
				{
					this.OndeductdepositamountChanging(value);
					this.SendPropertyChanging();
					this._deductdepositamount = value;
					this.SendPropertyChanged("deductdepositamount");
					this.OndeductdepositamountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_redoInputviry", DbType="Bit NOT NULL")]
		public bool redoInputviry
		{
			get
			{
				return this._redoInputviry;
			}
			set
			{
				if ((this._redoInputviry != value))
				{
					this.OnredoInputviryChanging(value);
					this.SendPropertyChanging();
					this._redoInputviry = value;
					this.SendPropertyChanged("redoInputviry");
					this.OnredoInputviryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uploadpriviousPriod", DbType="Bit NOT NULL")]
		public bool uploadpriviousPriod
		{
			get
			{
				return this._uploadpriviousPriod;
			}
			set
			{
				if ((this._uploadpriviousPriod != value))
				{
					this.OnuploadpriviousPriodChanging(value);
					this.SendPropertyChanging();
					this._uploadpriviousPriod = value;
					this.SendPropertyChanged("uploadpriviousPriod");
					this.OnuploadpriviousPriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagesign", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary imagesign
		{
			get
			{
				return this._imagesign;
			}
			set
			{
				if ((this._imagesign != value))
				{
					this.OnimagesignChanging(value);
					this.SendPropertyChanging();
					this._imagesign = value;
					this.SendPropertyChanged("imagesign");
					this.OnimagesignChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nationKA", DbType="Bit NOT NULL")]
		public bool nationKA
		{
			get
			{
				return this._nationKA;
			}
			set
			{
				if ((this._nationKA != value))
				{
					this.OnnationKAChanging(value);
					this.SendPropertyChanging();
					this._nationKA = value;
					this.SendPropertyChanged("nationKA");
					this.OnnationKAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
