#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luckynumber
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Luckynumber")]
	public partial class LinqtoSQLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_ChecktongKM(tbl_ChecktongKM instance);
    partial void Updatetbl_ChecktongKM(tbl_ChecktongKM instance);
    partial void Deletetbl_ChecktongKM(tbl_ChecktongKM instance);
    partial void Inserttbl_Temp(tbl_Temp instance);
    partial void Updatetbl_Temp(tbl_Temp instance);
    partial void Deletetbl_Temp(tbl_Temp instance);
    partial void Inserttbl_CTKM(tbl_CTKM instance);
    partial void Updatetbl_CTKM(tbl_CTKM instance);
    partial void Deletetbl_CTKM(tbl_CTKM instance);
    partial void Inserttbl_NhomKHKM(tbl_NhomKHKM instance);
    partial void Updatetbl_NhomKHKM(tbl_NhomKHKM instance);
    partial void Deletetbl_NhomKHKM(tbl_NhomKHKM instance);
    partial void Inserttbl_Product(tbl_Product instance);
    partial void Updatetbl_Product(tbl_Product instance);
    partial void Deletetbl_Product(tbl_Product instance);
    partial void Inserttbl_SalesFreeOrder(tbl_SalesFreeOrder instance);
    partial void Updatetbl_SalesFreeOrder(tbl_SalesFreeOrder instance);
    partial void Deletetbl_SalesFreeOrder(tbl_SalesFreeOrder instance);
    partial void Inserttbl_Salesorder(tbl_Salesorder instance);
    partial void Updatetbl_Salesorder(tbl_Salesorder instance);
    partial void Deletetbl_Salesorder(tbl_Salesorder instance);
    partial void Inserttbl_SalesOrderFromFree(tbl_SalesOrderFromFree instance);
    partial void Updatetbl_SalesOrderFromFree(tbl_SalesOrderFromFree instance);
    partial void Deletetbl_SalesOrderFromFree(tbl_SalesOrderFromFree instance);
    #endregion
		
		public LinqtoSQLDataContext() : 
				base(global::Luckynumber.Properties.Settings.Default.LuckynumberConnectionString5, mappingSource)
		{
			OnCreated();
		}
		
		public LinqtoSQLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqtoSQLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqtoSQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqtoSQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_ChecktongKM> tbl_ChecktongKMs
		{
			get
			{
				return this.GetTable<tbl_ChecktongKM>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Temp> tbl_Temps
		{
			get
			{
				return this.GetTable<tbl_Temp>();
			}
		}
		
		public System.Data.Linq.Table<tbl_CTKM> tbl_CTKMs
		{
			get
			{
				return this.GetTable<tbl_CTKM>();
			}
		}
		
		public System.Data.Linq.Table<tbl_NhomKHKM> tbl_NhomKHKMs
		{
			get
			{
				return this.GetTable<tbl_NhomKHKM>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Product> tbl_Products
		{
			get
			{
				return this.GetTable<tbl_Product>();
			}
		}
		
		public System.Data.Linq.Table<tbl_SalesFreeOrder> tbl_SalesFreeOrders
		{
			get
			{
				return this.GetTable<tbl_SalesFreeOrder>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Salesorder> tbl_Salesorders
		{
			get
			{
				return this.GetTable<tbl_Salesorder>();
			}
		}
		
		public System.Data.Linq.Table<tbl_SalesOrderFromFree> tbl_SalesOrderFromFrees
		{
			get
			{
				return this.GetTable<tbl_SalesOrderFromFree>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ChecktongKM")]
	public partial class tbl_ChecktongKM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<double> _Sold_to_party;
		
		private string _Name;
		
		private int _id;
		
		private string _enduser;
		
		private string _maCTKM;
		
		private string _Ma_SP_Duoc_KM;
		
		private System.Nullable<double> _So_luong_duoc_KM;
		
		private System.Nullable<double> _So_luong_thuc_te_KM;
		
		private string _PO_message;
		
		private string _Sale_Region;
		
		private System.Nullable<double> _So_luong_hang_Mua;
		
		private System.Nullable<int> _STT;
		
		private string _TenCTKM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSold_to_partyChanging(System.Nullable<double> value);
    partial void OnSold_to_partyChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnenduserChanging(string value);
    partial void OnenduserChanged();
    partial void OnmaCTKMChanging(string value);
    partial void OnmaCTKMChanged();
    partial void OnMa_SP_Duoc_KMChanging(string value);
    partial void OnMa_SP_Duoc_KMChanged();
    partial void OnSo_luong_duoc_KMChanging(System.Nullable<double> value);
    partial void OnSo_luong_duoc_KMChanged();
    partial void OnSo_luong_thuc_te_KMChanging(System.Nullable<double> value);
    partial void OnSo_luong_thuc_te_KMChanged();
    partial void OnPO_messageChanging(string value);
    partial void OnPO_messageChanged();
    partial void OnSale_RegionChanging(string value);
    partial void OnSale_RegionChanged();
    partial void OnSo_luong_hang_MuaChanging(System.Nullable<double> value);
    partial void OnSo_luong_hang_MuaChanged();
    partial void OnSTTChanging(System.Nullable<int> value);
    partial void OnSTTChanged();
    partial void OnTenCTKMChanging(string value);
    partial void OnTenCTKMChanged();
    #endregion
		
		public tbl_ChecktongKM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sold_to_party", DbType="Float")]
		public System.Nullable<double> Sold_to_party
		{
			get
			{
				return this._Sold_to_party;
			}
			set
			{
				if ((this._Sold_to_party != value))
				{
					this.OnSold_to_partyChanging(value);
					this.SendPropertyChanging();
					this._Sold_to_party = value;
					this.SendPropertyChanged("Sold_to_party");
					this.OnSold_to_partyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enduser", DbType="NVarChar(255)")]
		public string enduser
		{
			get
			{
				return this._enduser;
			}
			set
			{
				if ((this._enduser != value))
				{
					this.OnenduserChanging(value);
					this.SendPropertyChanging();
					this._enduser = value;
					this.SendPropertyChanged("enduser");
					this.OnenduserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCTKM", DbType="NVarChar(255)")]
		public string maCTKM
		{
			get
			{
				return this._maCTKM;
			}
			set
			{
				if ((this._maCTKM != value))
				{
					this.OnmaCTKMChanging(value);
					this.SendPropertyChanging();
					this._maCTKM = value;
					this.SendPropertyChanged("maCTKM");
					this.OnmaCTKMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_SP_Duoc_KM", DbType="NVarChar(255)")]
		public string Ma_SP_Duoc_KM
		{
			get
			{
				return this._Ma_SP_Duoc_KM;
			}
			set
			{
				if ((this._Ma_SP_Duoc_KM != value))
				{
					this.OnMa_SP_Duoc_KMChanging(value);
					this.SendPropertyChanging();
					this._Ma_SP_Duoc_KM = value;
					this.SendPropertyChanged("Ma_SP_Duoc_KM");
					this.OnMa_SP_Duoc_KMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_luong_duoc_KM", DbType="Float")]
		public System.Nullable<double> So_luong_duoc_KM
		{
			get
			{
				return this._So_luong_duoc_KM;
			}
			set
			{
				if ((this._So_luong_duoc_KM != value))
				{
					this.OnSo_luong_duoc_KMChanging(value);
					this.SendPropertyChanging();
					this._So_luong_duoc_KM = value;
					this.SendPropertyChanged("So_luong_duoc_KM");
					this.OnSo_luong_duoc_KMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_luong_thuc_te_KM", DbType="Float")]
		public System.Nullable<double> So_luong_thuc_te_KM
		{
			get
			{
				return this._So_luong_thuc_te_KM;
			}
			set
			{
				if ((this._So_luong_thuc_te_KM != value))
				{
					this.OnSo_luong_thuc_te_KMChanging(value);
					this.SendPropertyChanging();
					this._So_luong_thuc_te_KM = value;
					this.SendPropertyChanged("So_luong_thuc_te_KM");
					this.OnSo_luong_thuc_te_KMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PO_message", DbType="NVarChar(255)")]
		public string PO_message
		{
			get
			{
				return this._PO_message;
			}
			set
			{
				if ((this._PO_message != value))
				{
					this.OnPO_messageChanging(value);
					this.SendPropertyChanging();
					this._PO_message = value;
					this.SendPropertyChanged("PO_message");
					this.OnPO_messageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sale_Region", DbType="NVarChar(255)")]
		public string Sale_Region
		{
			get
			{
				return this._Sale_Region;
			}
			set
			{
				if ((this._Sale_Region != value))
				{
					this.OnSale_RegionChanging(value);
					this.SendPropertyChanging();
					this._Sale_Region = value;
					this.SendPropertyChanged("Sale_Region");
					this.OnSale_RegionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_luong_hang_Mua", DbType="Float")]
		public System.Nullable<double> So_luong_hang_Mua
		{
			get
			{
				return this._So_luong_hang_Mua;
			}
			set
			{
				if ((this._So_luong_hang_Mua != value))
				{
					this.OnSo_luong_hang_MuaChanging(value);
					this.SendPropertyChanging();
					this._So_luong_hang_Mua = value;
					this.SendPropertyChanged("So_luong_hang_Mua");
					this.OnSo_luong_hang_MuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int")]
		public System.Nullable<int> STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCTKM", DbType="NVarChar(255)")]
		public string TenCTKM
		{
			get
			{
				return this._TenCTKM;
			}
			set
			{
				if ((this._TenCTKM != value))
				{
					this.OnTenCTKMChanging(value);
					this.SendPropertyChanging();
					this._TenCTKM = value;
					this.SendPropertyChanged("TenCTKM");
					this.OnTenCTKMChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Temp")]
	public partial class tbl_Temp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _Version;
		
		private string _enduser;
		
		private string _password;
		
		private bool _OrderFree;
		
		private bool _Orderbuy;
		
		private bool _Totalreports;
		
		private System.Data.Linq.Binary _imagesign;
		
		private bool _Lkright;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnVersionChanging(System.Nullable<int> value);
    partial void OnVersionChanged();
    partial void OnenduserChanging(string value);
    partial void OnenduserChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnOrderFreeChanging(bool value);
    partial void OnOrderFreeChanged();
    partial void OnOrderbuyChanging(bool value);
    partial void OnOrderbuyChanged();
    partial void OnTotalreportsChanging(bool value);
    partial void OnTotalreportsChanged();
    partial void OnimagesignChanging(System.Data.Linq.Binary value);
    partial void OnimagesignChanged();
    partial void OnLkrightChanging(bool value);
    partial void OnLkrightChanged();
    #endregion
		
		public tbl_Temp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="Int")]
		public System.Nullable<int> Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this.OnVersionChanging(value);
					this.SendPropertyChanging();
					this._Version = value;
					this.SendPropertyChanged("Version");
					this.OnVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enduser", DbType="NChar(225)")]
		public string enduser
		{
			get
			{
				return this._enduser;
			}
			set
			{
				if ((this._enduser != value))
				{
					this.OnenduserChanging(value);
					this.SendPropertyChanging();
					this._enduser = value;
					this.SendPropertyChanged("enduser");
					this.OnenduserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NChar(225)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderFree", DbType="Bit NOT NULL")]
		public bool OrderFree
		{
			get
			{
				return this._OrderFree;
			}
			set
			{
				if ((this._OrderFree != value))
				{
					this.OnOrderFreeChanging(value);
					this.SendPropertyChanging();
					this._OrderFree = value;
					this.SendPropertyChanged("OrderFree");
					this.OnOrderFreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orderbuy", DbType="Bit NOT NULL")]
		public bool Orderbuy
		{
			get
			{
				return this._Orderbuy;
			}
			set
			{
				if ((this._Orderbuy != value))
				{
					this.OnOrderbuyChanging(value);
					this.SendPropertyChanging();
					this._Orderbuy = value;
					this.SendPropertyChanged("Orderbuy");
					this.OnOrderbuyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Totalreports", DbType="Bit NOT NULL")]
		public bool Totalreports
		{
			get
			{
				return this._Totalreports;
			}
			set
			{
				if ((this._Totalreports != value))
				{
					this.OnTotalreportsChanging(value);
					this.SendPropertyChanging();
					this._Totalreports = value;
					this.SendPropertyChanged("Totalreports");
					this.OnTotalreportsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagesign", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary imagesign
		{
			get
			{
				return this._imagesign;
			}
			set
			{
				if ((this._imagesign != value))
				{
					this.OnimagesignChanging(value);
					this.SendPropertyChanging();
					this._imagesign = value;
					this.SendPropertyChanged("imagesign");
					this.OnimagesignChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lkright", DbType="Bit NOT NULL")]
		public bool Lkright
		{
			get
			{
				return this._Lkright;
			}
			set
			{
				if ((this._Lkright != value))
				{
					this.OnLkrightChanging(value);
					this.SendPropertyChanging();
					this._Lkright = value;
					this.SendPropertyChanged("Lkright");
					this.OnLkrightChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_CTKM")]
	public partial class tbl_CTKM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mã_CT;
		
		private string _SaleOrg;
		
		private string _PO_Message;
		
		private string _Mã_SP_Mua;
		
		private string _Mã_SP_KM;
		
		private string _Tên_SP_mua;
		
		private string _Tên_SP_KM;
		
		private System.Nullable<double> _Tỷ_lệ_CTKM;
		
		private System.Nullable<System.DateTime> _Từ_ngày;
		
		private System.Nullable<System.DateTime> _Đến_Ngày;
		
		private string _Nhóm_khách_hàng;
		
		private string _enduser;
		
		private int _id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMã_CTChanging(string value);
    partial void OnMã_CTChanged();
    partial void OnSaleOrgChanging(string value);
    partial void OnSaleOrgChanged();
    partial void OnPO_MessageChanging(string value);
    partial void OnPO_MessageChanged();
    partial void OnMã_SP_MuaChanging(string value);
    partial void OnMã_SP_MuaChanged();
    partial void OnMã_SP_KMChanging(string value);
    partial void OnMã_SP_KMChanged();
    partial void OnTên_SP_muaChanging(string value);
    partial void OnTên_SP_muaChanged();
    partial void OnTên_SP_KMChanging(string value);
    partial void OnTên_SP_KMChanged();
    partial void OnTỷ_lệ_CTKMChanging(System.Nullable<double> value);
    partial void OnTỷ_lệ_CTKMChanged();
    partial void OnTừ_ngàyChanging(System.Nullable<System.DateTime> value);
    partial void OnTừ_ngàyChanged();
    partial void OnĐến_NgàyChanging(System.Nullable<System.DateTime> value);
    partial void OnĐến_NgàyChanged();
    partial void OnNhóm_khách_hàngChanging(string value);
    partial void OnNhóm_khách_hàngChanged();
    partial void OnenduserChanging(string value);
    partial void OnenduserChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    #endregion
		
		public tbl_CTKM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã CT]", Storage="_Mã_CT", DbType="NVarChar(255)")]
		public string Mã_CT
		{
			get
			{
				return this._Mã_CT;
			}
			set
			{
				if ((this._Mã_CT != value))
				{
					this.OnMã_CTChanging(value);
					this.SendPropertyChanging();
					this._Mã_CT = value;
					this.SendPropertyChanged("Mã_CT");
					this.OnMã_CTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaleOrg", DbType="NVarChar(255)")]
		public string SaleOrg
		{
			get
			{
				return this._SaleOrg;
			}
			set
			{
				if ((this._SaleOrg != value))
				{
					this.OnSaleOrgChanging(value);
					this.SendPropertyChanging();
					this._SaleOrg = value;
					this.SendPropertyChanged("SaleOrg");
					this.OnSaleOrgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PO Message]", Storage="_PO_Message", DbType="NVarChar(255)")]
		public string PO_Message
		{
			get
			{
				return this._PO_Message;
			}
			set
			{
				if ((this._PO_Message != value))
				{
					this.OnPO_MessageChanging(value);
					this.SendPropertyChanging();
					this._PO_Message = value;
					this.SendPropertyChanged("PO_Message");
					this.OnPO_MessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã SP Mua]", Storage="_Mã_SP_Mua", DbType="NVarChar(255)")]
		public string Mã_SP_Mua
		{
			get
			{
				return this._Mã_SP_Mua;
			}
			set
			{
				if ((this._Mã_SP_Mua != value))
				{
					this.OnMã_SP_MuaChanging(value);
					this.SendPropertyChanging();
					this._Mã_SP_Mua = value;
					this.SendPropertyChanged("Mã_SP_Mua");
					this.OnMã_SP_MuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã SP KM]", Storage="_Mã_SP_KM", DbType="NVarChar(255)")]
		public string Mã_SP_KM
		{
			get
			{
				return this._Mã_SP_KM;
			}
			set
			{
				if ((this._Mã_SP_KM != value))
				{
					this.OnMã_SP_KMChanging(value);
					this.SendPropertyChanging();
					this._Mã_SP_KM = value;
					this.SendPropertyChanged("Mã_SP_KM");
					this.OnMã_SP_KMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tên SP mua]", Storage="_Tên_SP_mua", DbType="NVarChar(255)")]
		public string Tên_SP_mua
		{
			get
			{
				return this._Tên_SP_mua;
			}
			set
			{
				if ((this._Tên_SP_mua != value))
				{
					this.OnTên_SP_muaChanging(value);
					this.SendPropertyChanging();
					this._Tên_SP_mua = value;
					this.SendPropertyChanged("Tên_SP_mua");
					this.OnTên_SP_muaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tên SP KM]", Storage="_Tên_SP_KM", DbType="NVarChar(255)")]
		public string Tên_SP_KM
		{
			get
			{
				return this._Tên_SP_KM;
			}
			set
			{
				if ((this._Tên_SP_KM != value))
				{
					this.OnTên_SP_KMChanging(value);
					this.SendPropertyChanging();
					this._Tên_SP_KM = value;
					this.SendPropertyChanged("Tên_SP_KM");
					this.OnTên_SP_KMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tỷ lệ CTKM]", Storage="_Tỷ_lệ_CTKM", DbType="Float")]
		public System.Nullable<double> Tỷ_lệ_CTKM
		{
			get
			{
				return this._Tỷ_lệ_CTKM;
			}
			set
			{
				if ((this._Tỷ_lệ_CTKM != value))
				{
					this.OnTỷ_lệ_CTKMChanging(value);
					this.SendPropertyChanging();
					this._Tỷ_lệ_CTKM = value;
					this.SendPropertyChanged("Tỷ_lệ_CTKM");
					this.OnTỷ_lệ_CTKMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Từ ngày]", Storage="_Từ_ngày", DbType="DateTime")]
		public System.Nullable<System.DateTime> Từ_ngày
		{
			get
			{
				return this._Từ_ngày;
			}
			set
			{
				if ((this._Từ_ngày != value))
				{
					this.OnTừ_ngàyChanging(value);
					this.SendPropertyChanging();
					this._Từ_ngày = value;
					this.SendPropertyChanged("Từ_ngày");
					this.OnTừ_ngàyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Đến Ngày]", Storage="_Đến_Ngày", DbType="DateTime")]
		public System.Nullable<System.DateTime> Đến_Ngày
		{
			get
			{
				return this._Đến_Ngày;
			}
			set
			{
				if ((this._Đến_Ngày != value))
				{
					this.OnĐến_NgàyChanging(value);
					this.SendPropertyChanging();
					this._Đến_Ngày = value;
					this.SendPropertyChanged("Đến_Ngày");
					this.OnĐến_NgàyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nhóm khách hàng]", Storage="_Nhóm_khách_hàng", DbType="NVarChar(255)")]
		public string Nhóm_khách_hàng
		{
			get
			{
				return this._Nhóm_khách_hàng;
			}
			set
			{
				if ((this._Nhóm_khách_hàng != value))
				{
					this.OnNhóm_khách_hàngChanging(value);
					this.SendPropertyChanging();
					this._Nhóm_khách_hàng = value;
					this.SendPropertyChanged("Nhóm_khách_hàng");
					this.OnNhóm_khách_hàngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enduser", DbType="NVarChar(255)")]
		public string enduser
		{
			get
			{
				return this._enduser;
			}
			set
			{
				if ((this._enduser != value))
				{
					this.OnenduserChanging(value);
					this.SendPropertyChanging();
					this._enduser = value;
					this.SendPropertyChanged("enduser");
					this.OnenduserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_NhomKHKM")]
	public partial class tbl_NhomKHKM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mã_nhóm_KH;
		
		private System.Nullable<double> _CodeKH;
		
		private int _id;
		
		private string _enduser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMã_nhóm_KHChanging(string value);
    partial void OnMã_nhóm_KHChanged();
    partial void OnCodeKHChanging(System.Nullable<double> value);
    partial void OnCodeKHChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnenduserChanging(string value);
    partial void OnenduserChanged();
    #endregion
		
		public tbl_NhomKHKM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mã_nhóm_KH", DbType="NVarChar(30)")]
		public string Mã_nhóm_KH
		{
			get
			{
				return this._Mã_nhóm_KH;
			}
			set
			{
				if ((this._Mã_nhóm_KH != value))
				{
					this.OnMã_nhóm_KHChanging(value);
					this.SendPropertyChanging();
					this._Mã_nhóm_KH = value;
					this.SendPropertyChanged("Mã_nhóm_KH");
					this.OnMã_nhóm_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeKH", DbType="Float")]
		public System.Nullable<double> CodeKH
		{
			get
			{
				return this._CodeKH;
			}
			set
			{
				if ((this._CodeKH != value))
				{
					this.OnCodeKHChanging(value);
					this.SendPropertyChanging();
					this._CodeKH = value;
					this.SendPropertyChanged("CodeKH");
					this.OnCodeKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enduser", DbType="NVarChar(225)")]
		public string enduser
		{
			get
			{
				return this._enduser;
			}
			set
			{
				if ((this._enduser != value))
				{
					this.OnenduserChanging(value);
					this.SendPropertyChanging();
					this._enduser = value;
					this.SendPropertyChanged("enduser");
					this.OnenduserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Product")]
	public partial class tbl_Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Marterial_code;
		
		private string _Marterial_name;
		
		private string _Pack_size;
		
		private System.Nullable<double> _PC_Quy_chuan;
		
		private System.Nullable<double> _UC_Rate;
		
		private int _id;
		
		private string _enduser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMarterial_codeChanging(string value);
    partial void OnMarterial_codeChanged();
    partial void OnMarterial_nameChanging(string value);
    partial void OnMarterial_nameChanged();
    partial void OnPack_sizeChanging(string value);
    partial void OnPack_sizeChanged();
    partial void OnPC_Quy_chuanChanging(System.Nullable<double> value);
    partial void OnPC_Quy_chuanChanged();
    partial void OnUC_RateChanging(System.Nullable<double> value);
    partial void OnUC_RateChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnenduserChanging(string value);
    partial void OnenduserChanged();
    #endregion
		
		public tbl_Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Marterial code]", Storage="_Marterial_code", DbType="NVarChar(255)")]
		public string Marterial_code
		{
			get
			{
				return this._Marterial_code;
			}
			set
			{
				if ((this._Marterial_code != value))
				{
					this.OnMarterial_codeChanging(value);
					this.SendPropertyChanging();
					this._Marterial_code = value;
					this.SendPropertyChanged("Marterial_code");
					this.OnMarterial_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Marterial name]", Storage="_Marterial_name", DbType="NVarChar(255)")]
		public string Marterial_name
		{
			get
			{
				return this._Marterial_name;
			}
			set
			{
				if ((this._Marterial_name != value))
				{
					this.OnMarterial_nameChanging(value);
					this.SendPropertyChanging();
					this._Marterial_name = value;
					this.SendPropertyChanged("Marterial_name");
					this.OnMarterial_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Pack size]", Storage="_Pack_size", DbType="NVarChar(255)")]
		public string Pack_size
		{
			get
			{
				return this._Pack_size;
			}
			set
			{
				if ((this._Pack_size != value))
				{
					this.OnPack_sizeChanging(value);
					this.SendPropertyChanging();
					this._Pack_size = value;
					this.SendPropertyChanged("Pack_size");
					this.OnPack_sizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PC Quy chuan]", Storage="_PC_Quy_chuan", DbType="Float")]
		public System.Nullable<double> PC_Quy_chuan
		{
			get
			{
				return this._PC_Quy_chuan;
			}
			set
			{
				if ((this._PC_Quy_chuan != value))
				{
					this.OnPC_Quy_chuanChanging(value);
					this.SendPropertyChanging();
					this._PC_Quy_chuan = value;
					this.SendPropertyChanged("PC_Quy_chuan");
					this.OnPC_Quy_chuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[UC Rate]", Storage="_UC_Rate", DbType="Float")]
		public System.Nullable<double> UC_Rate
		{
			get
			{
				return this._UC_Rate;
			}
			set
			{
				if ((this._UC_Rate != value))
				{
					this.OnUC_RateChanging(value);
					this.SendPropertyChanging();
					this._UC_Rate = value;
					this.SendPropertyChanged("UC_Rate");
					this.OnUC_RateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enduser", DbType="NVarChar(255)")]
		public string enduser
		{
			get
			{
				return this._enduser;
			}
			set
			{
				if ((this._enduser != value))
				{
					this.OnenduserChanging(value);
					this.SendPropertyChanging();
					this._enduser = value;
					this.SendPropertyChanged("enduser");
					this.OnenduserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_SalesFreeOrder")]
	public partial class tbl_SalesFreeOrder : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Created;
		
		private System.Nullable<System.DateTime> _Dlv_Date;
		
		private string _SOrg;
		
		private string _PO_number;
		
		private string _ma_CTKM;
		
		private string _New_PO_number;
		
		private System.Nullable<double> _Order_Number;
		
		private string _Material;
		
		private string _Description;
		
		private System.Nullable<double> _Sold_to_party;
		
		private string _Name;
		
		private System.Nullable<System.DateTime> _Doc_Date;
		
		private System.Nullable<double> _Order_quantity;
		
		private System.Nullable<double> _ConfirmQty;
		
		private string _Status;
		
		private System.Nullable<double> _Item;
		
		private System.Nullable<double> _Net_price;
		
		private string _Rj;
		
		private string _Plnt;
		
		private System.Nullable<double> _Net_value;
		
		private int _id;
		
		private System.Nullable<double> _byOrder;
		
		private bool _rptselect;
		
		private string _enduser;
		
		private string _maNhomKHKM;
		
		private bool _wrongmessage;
		
		private bool _outofdate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCreatedChanging(string value);
    partial void OnCreatedChanged();
    partial void OnDlv_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnDlv_DateChanged();
    partial void OnSOrgChanging(string value);
    partial void OnSOrgChanged();
    partial void OnPO_numberChanging(string value);
    partial void OnPO_numberChanged();
    partial void Onma_CTKMChanging(string value);
    partial void Onma_CTKMChanged();
    partial void OnNew_PO_numberChanging(string value);
    partial void OnNew_PO_numberChanged();
    partial void OnOrder_NumberChanging(System.Nullable<double> value);
    partial void OnOrder_NumberChanged();
    partial void OnMaterialChanging(string value);
    partial void OnMaterialChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnSold_to_partyChanging(System.Nullable<double> value);
    partial void OnSold_to_partyChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDoc_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnDoc_DateChanged();
    partial void OnOrder_quantityChanging(System.Nullable<double> value);
    partial void OnOrder_quantityChanged();
    partial void OnConfirmQtyChanging(System.Nullable<double> value);
    partial void OnConfirmQtyChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnItemChanging(System.Nullable<double> value);
    partial void OnItemChanged();
    partial void OnNet_priceChanging(System.Nullable<double> value);
    partial void OnNet_priceChanged();
    partial void OnRjChanging(string value);
    partial void OnRjChanged();
    partial void OnPlntChanging(string value);
    partial void OnPlntChanged();
    partial void OnNet_valueChanging(System.Nullable<double> value);
    partial void OnNet_valueChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnbyOrderChanging(System.Nullable<double> value);
    partial void OnbyOrderChanged();
    partial void OnrptselectChanging(bool value);
    partial void OnrptselectChanged();
    partial void OnenduserChanging(string value);
    partial void OnenduserChanged();
    partial void OnmaNhomKHKMChanging(string value);
    partial void OnmaNhomKHKMChanged();
    partial void OnwrongmessageChanging(bool value);
    partial void OnwrongmessageChanged();
    partial void OnoutofdateChanging(bool value);
    partial void OnoutofdateChanged();
    #endregion
		
		public tbl_SalesFreeOrder()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="NVarChar(255)")]
		public string Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dlv_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Dlv_Date
		{
			get
			{
				return this._Dlv_Date;
			}
			set
			{
				if ((this._Dlv_Date != value))
				{
					this.OnDlv_DateChanging(value);
					this.SendPropertyChanging();
					this._Dlv_Date = value;
					this.SendPropertyChanged("Dlv_Date");
					this.OnDlv_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOrg", DbType="NVarChar(255)")]
		public string SOrg
		{
			get
			{
				return this._SOrg;
			}
			set
			{
				if ((this._SOrg != value))
				{
					this.OnSOrgChanging(value);
					this.SendPropertyChanging();
					this._SOrg = value;
					this.SendPropertyChanged("SOrg");
					this.OnSOrgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PO_number", DbType="NVarChar(255)")]
		public string PO_number
		{
			get
			{
				return this._PO_number;
			}
			set
			{
				if ((this._PO_number != value))
				{
					this.OnPO_numberChanging(value);
					this.SendPropertyChanging();
					this._PO_number = value;
					this.SendPropertyChanged("PO_number");
					this.OnPO_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_CTKM", DbType="NVarChar(255)")]
		public string ma_CTKM
		{
			get
			{
				return this._ma_CTKM;
			}
			set
			{
				if ((this._ma_CTKM != value))
				{
					this.Onma_CTKMChanging(value);
					this.SendPropertyChanging();
					this._ma_CTKM = value;
					this.SendPropertyChanged("ma_CTKM");
					this.Onma_CTKMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_New_PO_number", DbType="NVarChar(255)")]
		public string New_PO_number
		{
			get
			{
				return this._New_PO_number;
			}
			set
			{
				if ((this._New_PO_number != value))
				{
					this.OnNew_PO_numberChanging(value);
					this.SendPropertyChanging();
					this._New_PO_number = value;
					this.SendPropertyChanged("New_PO_number");
					this.OnNew_PO_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Order_Number", DbType="Float")]
		public System.Nullable<double> Order_Number
		{
			get
			{
				return this._Order_Number;
			}
			set
			{
				if ((this._Order_Number != value))
				{
					this.OnOrder_NumberChanging(value);
					this.SendPropertyChanging();
					this._Order_Number = value;
					this.SendPropertyChanged("Order_Number");
					this.OnOrder_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Material", DbType="NVarChar(255)")]
		public string Material
		{
			get
			{
				return this._Material;
			}
			set
			{
				if ((this._Material != value))
				{
					this.OnMaterialChanging(value);
					this.SendPropertyChanging();
					this._Material = value;
					this.SendPropertyChanged("Material");
					this.OnMaterialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(255)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sold_to_party", DbType="Float")]
		public System.Nullable<double> Sold_to_party
		{
			get
			{
				return this._Sold_to_party;
			}
			set
			{
				if ((this._Sold_to_party != value))
				{
					this.OnSold_to_partyChanging(value);
					this.SendPropertyChanging();
					this._Sold_to_party = value;
					this.SendPropertyChanged("Sold_to_party");
					this.OnSold_to_partyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doc_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Doc_Date
		{
			get
			{
				return this._Doc_Date;
			}
			set
			{
				if ((this._Doc_Date != value))
				{
					this.OnDoc_DateChanging(value);
					this.SendPropertyChanging();
					this._Doc_Date = value;
					this.SendPropertyChanged("Doc_Date");
					this.OnDoc_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Order_quantity", DbType="Float")]
		public System.Nullable<double> Order_quantity
		{
			get
			{
				return this._Order_quantity;
			}
			set
			{
				if ((this._Order_quantity != value))
				{
					this.OnOrder_quantityChanging(value);
					this.SendPropertyChanging();
					this._Order_quantity = value;
					this.SendPropertyChanged("Order_quantity");
					this.OnOrder_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmQty", DbType="Float")]
		public System.Nullable<double> ConfirmQty
		{
			get
			{
				return this._ConfirmQty;
			}
			set
			{
				if ((this._ConfirmQty != value))
				{
					this.OnConfirmQtyChanging(value);
					this.SendPropertyChanging();
					this._ConfirmQty = value;
					this.SendPropertyChanged("ConfirmQty");
					this.OnConfirmQtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(255)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item", DbType="Float")]
		public System.Nullable<double> Item
		{
			get
			{
				return this._Item;
			}
			set
			{
				if ((this._Item != value))
				{
					this.OnItemChanging(value);
					this.SendPropertyChanging();
					this._Item = value;
					this.SendPropertyChanged("Item");
					this.OnItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Net_price", DbType="Float")]
		public System.Nullable<double> Net_price
		{
			get
			{
				return this._Net_price;
			}
			set
			{
				if ((this._Net_price != value))
				{
					this.OnNet_priceChanging(value);
					this.SendPropertyChanging();
					this._Net_price = value;
					this.SendPropertyChanged("Net_price");
					this.OnNet_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rj", DbType="NVarChar(255)")]
		public string Rj
		{
			get
			{
				return this._Rj;
			}
			set
			{
				if ((this._Rj != value))
				{
					this.OnRjChanging(value);
					this.SendPropertyChanging();
					this._Rj = value;
					this.SendPropertyChanged("Rj");
					this.OnRjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Plnt", DbType="NVarChar(255)")]
		public string Plnt
		{
			get
			{
				return this._Plnt;
			}
			set
			{
				if ((this._Plnt != value))
				{
					this.OnPlntChanging(value);
					this.SendPropertyChanging();
					this._Plnt = value;
					this.SendPropertyChanged("Plnt");
					this.OnPlntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Net_value", DbType="Float")]
		public System.Nullable<double> Net_value
		{
			get
			{
				return this._Net_value;
			}
			set
			{
				if ((this._Net_value != value))
				{
					this.OnNet_valueChanging(value);
					this.SendPropertyChanging();
					this._Net_value = value;
					this.SendPropertyChanged("Net_value");
					this.OnNet_valueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_byOrder", DbType="Float")]
		public System.Nullable<double> byOrder
		{
			get
			{
				return this._byOrder;
			}
			set
			{
				if ((this._byOrder != value))
				{
					this.OnbyOrderChanging(value);
					this.SendPropertyChanging();
					this._byOrder = value;
					this.SendPropertyChanged("byOrder");
					this.OnbyOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rptselect", DbType="Bit NOT NULL")]
		public bool rptselect
		{
			get
			{
				return this._rptselect;
			}
			set
			{
				if ((this._rptselect != value))
				{
					this.OnrptselectChanging(value);
					this.SendPropertyChanging();
					this._rptselect = value;
					this.SendPropertyChanged("rptselect");
					this.OnrptselectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enduser", DbType="NVarChar(255)")]
		public string enduser
		{
			get
			{
				return this._enduser;
			}
			set
			{
				if ((this._enduser != value))
				{
					this.OnenduserChanging(value);
					this.SendPropertyChanging();
					this._enduser = value;
					this.SendPropertyChanged("enduser");
					this.OnenduserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhomKHKM", DbType="NVarChar(255)")]
		public string maNhomKHKM
		{
			get
			{
				return this._maNhomKHKM;
			}
			set
			{
				if ((this._maNhomKHKM != value))
				{
					this.OnmaNhomKHKMChanging(value);
					this.SendPropertyChanging();
					this._maNhomKHKM = value;
					this.SendPropertyChanged("maNhomKHKM");
					this.OnmaNhomKHKMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wrongmessage", DbType="Bit NOT NULL")]
		public bool wrongmessage
		{
			get
			{
				return this._wrongmessage;
			}
			set
			{
				if ((this._wrongmessage != value))
				{
					this.OnwrongmessageChanging(value);
					this.SendPropertyChanging();
					this._wrongmessage = value;
					this.SendPropertyChanged("wrongmessage");
					this.OnwrongmessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outofdate", DbType="Bit NOT NULL")]
		public bool outofdate
		{
			get
			{
				return this._outofdate;
			}
			set
			{
				if ((this._outofdate != value))
				{
					this.OnoutofdateChanging(value);
					this.SendPropertyChanging();
					this._outofdate = value;
					this.SendPropertyChanged("outofdate");
					this.OnoutofdateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Salesorder")]
	public partial class tbl_Salesorder : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Created;
		
		private string _SOrg;
		
		private string _PO_number;
		
		private System.Nullable<System.DateTime> _Doc_Date;
		
		private System.Nullable<System.DateTime> _Dlv_Date;
		
		private System.Nullable<double> _Order_Number;
		
		private System.Nullable<double> _Sold_to_party;
		
		private string _Name;
		
		private string _Material;
		
		private string _Description;
		
		private System.Nullable<double> _Order_quantity;
		
		private System.Nullable<double> _ConfirmQty;
		
		private string _Status;
		
		private System.Nullable<double> _Item;
		
		private System.Nullable<double> _Net_price;
		
		private string _Rj;
		
		private string _Plnt;
		
		private System.Nullable<double> _Net_value;
		
		private int _id;
		
		private bool _selectprt;
		
		private string _enduser;
		
		private string _maCTKM;
		
		private string _Ma_SP_Duoc_KM;
		
		private System.Nullable<double> _So_luong_duoc_KM;
		
		private string _Mã_nhóm_KH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCreatedChanging(string value);
    partial void OnCreatedChanged();
    partial void OnSOrgChanging(string value);
    partial void OnSOrgChanged();
    partial void OnPO_numberChanging(string value);
    partial void OnPO_numberChanged();
    partial void OnDoc_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnDoc_DateChanged();
    partial void OnDlv_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnDlv_DateChanged();
    partial void OnOrder_NumberChanging(System.Nullable<double> value);
    partial void OnOrder_NumberChanged();
    partial void OnSold_to_partyChanging(System.Nullable<double> value);
    partial void OnSold_to_partyChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnMaterialChanging(string value);
    partial void OnMaterialChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnOrder_quantityChanging(System.Nullable<double> value);
    partial void OnOrder_quantityChanged();
    partial void OnConfirmQtyChanging(System.Nullable<double> value);
    partial void OnConfirmQtyChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnItemChanging(System.Nullable<double> value);
    partial void OnItemChanged();
    partial void OnNet_priceChanging(System.Nullable<double> value);
    partial void OnNet_priceChanged();
    partial void OnRjChanging(string value);
    partial void OnRjChanged();
    partial void OnPlntChanging(string value);
    partial void OnPlntChanged();
    partial void OnNet_valueChanging(System.Nullable<double> value);
    partial void OnNet_valueChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnselectprtChanging(bool value);
    partial void OnselectprtChanged();
    partial void OnenduserChanging(string value);
    partial void OnenduserChanged();
    partial void OnmaCTKMChanging(string value);
    partial void OnmaCTKMChanged();
    partial void OnMa_SP_Duoc_KMChanging(string value);
    partial void OnMa_SP_Duoc_KMChanged();
    partial void OnSo_luong_duoc_KMChanging(System.Nullable<double> value);
    partial void OnSo_luong_duoc_KMChanged();
    partial void OnMã_nhóm_KHChanging(string value);
    partial void OnMã_nhóm_KHChanged();
    #endregion
		
		public tbl_Salesorder()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="NVarChar(255)")]
		public string Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOrg", DbType="NVarChar(255)")]
		public string SOrg
		{
			get
			{
				return this._SOrg;
			}
			set
			{
				if ((this._SOrg != value))
				{
					this.OnSOrgChanging(value);
					this.SendPropertyChanging();
					this._SOrg = value;
					this.SendPropertyChanged("SOrg");
					this.OnSOrgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PO_number", DbType="NVarChar(255)")]
		public string PO_number
		{
			get
			{
				return this._PO_number;
			}
			set
			{
				if ((this._PO_number != value))
				{
					this.OnPO_numberChanging(value);
					this.SendPropertyChanging();
					this._PO_number = value;
					this.SendPropertyChanged("PO_number");
					this.OnPO_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doc_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Doc_Date
		{
			get
			{
				return this._Doc_Date;
			}
			set
			{
				if ((this._Doc_Date != value))
				{
					this.OnDoc_DateChanging(value);
					this.SendPropertyChanging();
					this._Doc_Date = value;
					this.SendPropertyChanged("Doc_Date");
					this.OnDoc_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dlv_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Dlv_Date
		{
			get
			{
				return this._Dlv_Date;
			}
			set
			{
				if ((this._Dlv_Date != value))
				{
					this.OnDlv_DateChanging(value);
					this.SendPropertyChanging();
					this._Dlv_Date = value;
					this.SendPropertyChanged("Dlv_Date");
					this.OnDlv_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Order_Number", DbType="Float")]
		public System.Nullable<double> Order_Number
		{
			get
			{
				return this._Order_Number;
			}
			set
			{
				if ((this._Order_Number != value))
				{
					this.OnOrder_NumberChanging(value);
					this.SendPropertyChanging();
					this._Order_Number = value;
					this.SendPropertyChanged("Order_Number");
					this.OnOrder_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sold_to_party", DbType="Float")]
		public System.Nullable<double> Sold_to_party
		{
			get
			{
				return this._Sold_to_party;
			}
			set
			{
				if ((this._Sold_to_party != value))
				{
					this.OnSold_to_partyChanging(value);
					this.SendPropertyChanging();
					this._Sold_to_party = value;
					this.SendPropertyChanged("Sold_to_party");
					this.OnSold_to_partyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Material", DbType="NVarChar(255)")]
		public string Material
		{
			get
			{
				return this._Material;
			}
			set
			{
				if ((this._Material != value))
				{
					this.OnMaterialChanging(value);
					this.SendPropertyChanging();
					this._Material = value;
					this.SendPropertyChanged("Material");
					this.OnMaterialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(255)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Order_quantity", DbType="Float")]
		public System.Nullable<double> Order_quantity
		{
			get
			{
				return this._Order_quantity;
			}
			set
			{
				if ((this._Order_quantity != value))
				{
					this.OnOrder_quantityChanging(value);
					this.SendPropertyChanging();
					this._Order_quantity = value;
					this.SendPropertyChanged("Order_quantity");
					this.OnOrder_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmQty", DbType="Float")]
		public System.Nullable<double> ConfirmQty
		{
			get
			{
				return this._ConfirmQty;
			}
			set
			{
				if ((this._ConfirmQty != value))
				{
					this.OnConfirmQtyChanging(value);
					this.SendPropertyChanging();
					this._ConfirmQty = value;
					this.SendPropertyChanged("ConfirmQty");
					this.OnConfirmQtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(255)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item", DbType="Float")]
		public System.Nullable<double> Item
		{
			get
			{
				return this._Item;
			}
			set
			{
				if ((this._Item != value))
				{
					this.OnItemChanging(value);
					this.SendPropertyChanging();
					this._Item = value;
					this.SendPropertyChanged("Item");
					this.OnItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Net_price", DbType="Float")]
		public System.Nullable<double> Net_price
		{
			get
			{
				return this._Net_price;
			}
			set
			{
				if ((this._Net_price != value))
				{
					this.OnNet_priceChanging(value);
					this.SendPropertyChanging();
					this._Net_price = value;
					this.SendPropertyChanged("Net_price");
					this.OnNet_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rj", DbType="NVarChar(255)")]
		public string Rj
		{
			get
			{
				return this._Rj;
			}
			set
			{
				if ((this._Rj != value))
				{
					this.OnRjChanging(value);
					this.SendPropertyChanging();
					this._Rj = value;
					this.SendPropertyChanged("Rj");
					this.OnRjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Plnt", DbType="NVarChar(255)")]
		public string Plnt
		{
			get
			{
				return this._Plnt;
			}
			set
			{
				if ((this._Plnt != value))
				{
					this.OnPlntChanging(value);
					this.SendPropertyChanging();
					this._Plnt = value;
					this.SendPropertyChanged("Plnt");
					this.OnPlntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Net_value", DbType="Float")]
		public System.Nullable<double> Net_value
		{
			get
			{
				return this._Net_value;
			}
			set
			{
				if ((this._Net_value != value))
				{
					this.OnNet_valueChanging(value);
					this.SendPropertyChanging();
					this._Net_value = value;
					this.SendPropertyChanged("Net_value");
					this.OnNet_valueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_selectprt", DbType="Bit NOT NULL")]
		public bool selectprt
		{
			get
			{
				return this._selectprt;
			}
			set
			{
				if ((this._selectprt != value))
				{
					this.OnselectprtChanging(value);
					this.SendPropertyChanging();
					this._selectprt = value;
					this.SendPropertyChanged("selectprt");
					this.OnselectprtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enduser", DbType="NVarChar(255)")]
		public string enduser
		{
			get
			{
				return this._enduser;
			}
			set
			{
				if ((this._enduser != value))
				{
					this.OnenduserChanging(value);
					this.SendPropertyChanging();
					this._enduser = value;
					this.SendPropertyChanged("enduser");
					this.OnenduserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCTKM", DbType="NVarChar(255)")]
		public string maCTKM
		{
			get
			{
				return this._maCTKM;
			}
			set
			{
				if ((this._maCTKM != value))
				{
					this.OnmaCTKMChanging(value);
					this.SendPropertyChanging();
					this._maCTKM = value;
					this.SendPropertyChanged("maCTKM");
					this.OnmaCTKMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_SP_Duoc_KM", DbType="NVarChar(255)")]
		public string Ma_SP_Duoc_KM
		{
			get
			{
				return this._Ma_SP_Duoc_KM;
			}
			set
			{
				if ((this._Ma_SP_Duoc_KM != value))
				{
					this.OnMa_SP_Duoc_KMChanging(value);
					this.SendPropertyChanging();
					this._Ma_SP_Duoc_KM = value;
					this.SendPropertyChanged("Ma_SP_Duoc_KM");
					this.OnMa_SP_Duoc_KMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_luong_duoc_KM", DbType="Float")]
		public System.Nullable<double> So_luong_duoc_KM
		{
			get
			{
				return this._So_luong_duoc_KM;
			}
			set
			{
				if ((this._So_luong_duoc_KM != value))
				{
					this.OnSo_luong_duoc_KMChanging(value);
					this.SendPropertyChanging();
					this._So_luong_duoc_KM = value;
					this.SendPropertyChanged("So_luong_duoc_KM");
					this.OnSo_luong_duoc_KMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mã_nhóm_KH", DbType="NVarChar(30)")]
		public string Mã_nhóm_KH
		{
			get
			{
				return this._Mã_nhóm_KH;
			}
			set
			{
				if ((this._Mã_nhóm_KH != value))
				{
					this.OnMã_nhóm_KHChanging(value);
					this.SendPropertyChanging();
					this._Mã_nhóm_KH = value;
					this.SendPropertyChanged("Mã_nhóm_KH");
					this.OnMã_nhóm_KHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_SalesOrderFromFree")]
	public partial class tbl_SalesOrderFromFree : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Created;
		
		private System.Nullable<System.DateTime> _Dlv_Date;
		
		private string _SOrg;
		
		private string _ma_CTKM;
		
		private System.Nullable<double> _Reference_Order_Number;
		
		private string _Material;
		
		private string _Description;
		
		private System.Nullable<double> _Sold_to_party;
		
		private string _Name;
		
		private System.Nullable<double> _Quantity;
		
		private int _id;
		
		private bool _rptselect;
		
		private string _enduser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCreatedChanging(string value);
    partial void OnCreatedChanged();
    partial void OnDlv_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnDlv_DateChanged();
    partial void OnSOrgChanging(string value);
    partial void OnSOrgChanged();
    partial void Onma_CTKMChanging(string value);
    partial void Onma_CTKMChanged();
    partial void OnReference_Order_NumberChanging(System.Nullable<double> value);
    partial void OnReference_Order_NumberChanged();
    partial void OnMaterialChanging(string value);
    partial void OnMaterialChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnSold_to_partyChanging(System.Nullable<double> value);
    partial void OnSold_to_partyChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnQuantityChanging(System.Nullable<double> value);
    partial void OnQuantityChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnrptselectChanging(bool value);
    partial void OnrptselectChanged();
    partial void OnenduserChanging(string value);
    partial void OnenduserChanged();
    #endregion
		
		public tbl_SalesOrderFromFree()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="NVarChar(255)")]
		public string Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dlv_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Dlv_Date
		{
			get
			{
				return this._Dlv_Date;
			}
			set
			{
				if ((this._Dlv_Date != value))
				{
					this.OnDlv_DateChanging(value);
					this.SendPropertyChanging();
					this._Dlv_Date = value;
					this.SendPropertyChanged("Dlv_Date");
					this.OnDlv_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOrg", DbType="NVarChar(255)")]
		public string SOrg
		{
			get
			{
				return this._SOrg;
			}
			set
			{
				if ((this._SOrg != value))
				{
					this.OnSOrgChanging(value);
					this.SendPropertyChanging();
					this._SOrg = value;
					this.SendPropertyChanged("SOrg");
					this.OnSOrgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_CTKM", DbType="NVarChar(255)")]
		public string ma_CTKM
		{
			get
			{
				return this._ma_CTKM;
			}
			set
			{
				if ((this._ma_CTKM != value))
				{
					this.Onma_CTKMChanging(value);
					this.SendPropertyChanging();
					this._ma_CTKM = value;
					this.SendPropertyChanged("ma_CTKM");
					this.Onma_CTKMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reference_Order_Number", DbType="Float")]
		public System.Nullable<double> Reference_Order_Number
		{
			get
			{
				return this._Reference_Order_Number;
			}
			set
			{
				if ((this._Reference_Order_Number != value))
				{
					this.OnReference_Order_NumberChanging(value);
					this.SendPropertyChanging();
					this._Reference_Order_Number = value;
					this.SendPropertyChanged("Reference_Order_Number");
					this.OnReference_Order_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Material", DbType="NVarChar(255)")]
		public string Material
		{
			get
			{
				return this._Material;
			}
			set
			{
				if ((this._Material != value))
				{
					this.OnMaterialChanging(value);
					this.SendPropertyChanging();
					this._Material = value;
					this.SendPropertyChanged("Material");
					this.OnMaterialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(255)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sold_to_party", DbType="Float")]
		public System.Nullable<double> Sold_to_party
		{
			get
			{
				return this._Sold_to_party;
			}
			set
			{
				if ((this._Sold_to_party != value))
				{
					this.OnSold_to_partyChanging(value);
					this.SendPropertyChanging();
					this._Sold_to_party = value;
					this.SendPropertyChanged("Sold_to_party");
					this.OnSold_to_partyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Float")]
		public System.Nullable<double> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rptselect", DbType="Bit NOT NULL")]
		public bool rptselect
		{
			get
			{
				return this._rptselect;
			}
			set
			{
				if ((this._rptselect != value))
				{
					this.OnrptselectChanging(value);
					this.SendPropertyChanging();
					this._rptselect = value;
					this.SendPropertyChanged("rptselect");
					this.OnrptselectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enduser", DbType="NVarChar(255)")]
		public string enduser
		{
			get
			{
				return this._enduser;
			}
			set
			{
				if ((this._enduser != value))
				{
					this.OnenduserChanging(value);
					this.SendPropertyChanging();
					this._enduser = value;
					this.SendPropertyChanged("enduser");
					this.OnenduserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
