#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arconfirmationletter
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Luckynumber")]
	public partial class LinqtoSQLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_CTKM(tbl_CTKM instance);
    partial void Updatetbl_CTKM(tbl_CTKM instance);
    partial void Deletetbl_CTKM(tbl_CTKM instance);
    partial void Inserttbl_Temp(tbl_Temp instance);
    partial void Updatetbl_Temp(tbl_Temp instance);
    partial void Deletetbl_Temp(tbl_Temp instance);
    partial void Inserttbl_NhomKHKM(tbl_NhomKHKM instance);
    partial void Updatetbl_NhomKHKM(tbl_NhomKHKM instance);
    partial void Deletetbl_NhomKHKM(tbl_NhomKHKM instance);
    partial void Inserttbl_Product(tbl_Product instance);
    partial void Updatetbl_Product(tbl_Product instance);
    partial void Deletetbl_Product(tbl_Product instance);
    partial void Inserttbl_rptnotEnought(tbl_rptnotEnought instance);
    partial void Updatetbl_rptnotEnought(tbl_rptnotEnought instance);
    partial void Deletetbl_rptnotEnought(tbl_rptnotEnought instance);
    partial void Inserttbl_SalesFreehavetopaid(tbl_SalesFreehavetopaid instance);
    partial void Updatetbl_SalesFreehavetopaid(tbl_SalesFreehavetopaid instance);
    partial void Deletetbl_SalesFreehavetopaid(tbl_SalesFreehavetopaid instance);
    partial void Inserttbl_SalesFreeOrder(tbl_SalesFreeOrder instance);
    partial void Updatetbl_SalesFreeOrder(tbl_SalesFreeOrder instance);
    partial void Deletetbl_SalesFreeOrder(tbl_SalesFreeOrder instance);
    partial void Inserttbl_Salesorder(tbl_Salesorder instance);
    partial void Updatetbl_Salesorder(tbl_Salesorder instance);
    partial void Deletetbl_Salesorder(tbl_Salesorder instance);
    #endregion
		
		public LinqtoSQLDataContext() : 
				base(global::arconfirmationletter.Properties.Settings.Default.LuckynumberConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqtoSQLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqtoSQLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqtoSQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqtoSQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_CTKM> tbl_CTKMs
		{
			get
			{
				return this.GetTable<tbl_CTKM>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Temp> tbl_Temps
		{
			get
			{
				return this.GetTable<tbl_Temp>();
			}
		}
		
		public System.Data.Linq.Table<tbl_NhomKHKM> tbl_NhomKHKMs
		{
			get
			{
				return this.GetTable<tbl_NhomKHKM>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Product> tbl_Products
		{
			get
			{
				return this.GetTable<tbl_Product>();
			}
		}
		
		public System.Data.Linq.Table<tbl_rptnotEnought> tbl_rptnotEnoughts
		{
			get
			{
				return this.GetTable<tbl_rptnotEnought>();
			}
		}
		
		public System.Data.Linq.Table<tbl_SalesFreehavetopaid> tbl_SalesFreehavetopaids
		{
			get
			{
				return this.GetTable<tbl_SalesFreehavetopaid>();
			}
		}
		
		public System.Data.Linq.Table<tbl_SalesFreeOrder> tbl_SalesFreeOrders
		{
			get
			{
				return this.GetTable<tbl_SalesFreeOrder>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Salesorder> tbl_Salesorders
		{
			get
			{
				return this.GetTable<tbl_Salesorder>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_CTKM")]
	public partial class tbl_CTKM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mã_CT;
		
		private string _PO_Message;
		
		private string _Mã_SP_Mua;
		
		private string _Mã_SP_KM;
		
		private string _Tên_SP_mua;
		
		private string _Tên_SP_KM;
		
		private System.Nullable<double> _Tỷ_lệ_CTKM;
		
		private System.Nullable<System.DateTime> _Từ_ngày;
		
		private System.Nullable<System.DateTime> _Đến_Ngày;
		
		private string _Nhóm_khách_hàng;
		
		private int _id;
		
		private string _enduser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMã_CTChanging(string value);
    partial void OnMã_CTChanged();
    partial void OnPO_MessageChanging(string value);
    partial void OnPO_MessageChanged();
    partial void OnMã_SP_MuaChanging(string value);
    partial void OnMã_SP_MuaChanged();
    partial void OnMã_SP_KMChanging(string value);
    partial void OnMã_SP_KMChanged();
    partial void OnTên_SP_muaChanging(string value);
    partial void OnTên_SP_muaChanged();
    partial void OnTên_SP_KMChanging(string value);
    partial void OnTên_SP_KMChanged();
    partial void OnTỷ_lệ_CTKMChanging(System.Nullable<double> value);
    partial void OnTỷ_lệ_CTKMChanged();
    partial void OnTừ_ngàyChanging(System.Nullable<System.DateTime> value);
    partial void OnTừ_ngàyChanged();
    partial void OnĐến_NgàyChanging(System.Nullable<System.DateTime> value);
    partial void OnĐến_NgàyChanged();
    partial void OnNhóm_khách_hàngChanging(string value);
    partial void OnNhóm_khách_hàngChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnenduserChanging(string value);
    partial void OnenduserChanged();
    #endregion
		
		public tbl_CTKM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã CT]", Storage="_Mã_CT", DbType="NVarChar(255)")]
		public string Mã_CT
		{
			get
			{
				return this._Mã_CT;
			}
			set
			{
				if ((this._Mã_CT != value))
				{
					this.OnMã_CTChanging(value);
					this.SendPropertyChanging();
					this._Mã_CT = value;
					this.SendPropertyChanged("Mã_CT");
					this.OnMã_CTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PO Message]", Storage="_PO_Message", DbType="NVarChar(255)")]
		public string PO_Message
		{
			get
			{
				return this._PO_Message;
			}
			set
			{
				if ((this._PO_Message != value))
				{
					this.OnPO_MessageChanging(value);
					this.SendPropertyChanging();
					this._PO_Message = value;
					this.SendPropertyChanged("PO_Message");
					this.OnPO_MessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã SP Mua]", Storage="_Mã_SP_Mua", DbType="NVarChar(255)")]
		public string Mã_SP_Mua
		{
			get
			{
				return this._Mã_SP_Mua;
			}
			set
			{
				if ((this._Mã_SP_Mua != value))
				{
					this.OnMã_SP_MuaChanging(value);
					this.SendPropertyChanging();
					this._Mã_SP_Mua = value;
					this.SendPropertyChanged("Mã_SP_Mua");
					this.OnMã_SP_MuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã SP KM]", Storage="_Mã_SP_KM", DbType="NVarChar(255)")]
		public string Mã_SP_KM
		{
			get
			{
				return this._Mã_SP_KM;
			}
			set
			{
				if ((this._Mã_SP_KM != value))
				{
					this.OnMã_SP_KMChanging(value);
					this.SendPropertyChanging();
					this._Mã_SP_KM = value;
					this.SendPropertyChanged("Mã_SP_KM");
					this.OnMã_SP_KMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tên SP mua]", Storage="_Tên_SP_mua", DbType="NVarChar(255)")]
		public string Tên_SP_mua
		{
			get
			{
				return this._Tên_SP_mua;
			}
			set
			{
				if ((this._Tên_SP_mua != value))
				{
					this.OnTên_SP_muaChanging(value);
					this.SendPropertyChanging();
					this._Tên_SP_mua = value;
					this.SendPropertyChanged("Tên_SP_mua");
					this.OnTên_SP_muaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tên SP KM]", Storage="_Tên_SP_KM", DbType="NVarChar(255)")]
		public string Tên_SP_KM
		{
			get
			{
				return this._Tên_SP_KM;
			}
			set
			{
				if ((this._Tên_SP_KM != value))
				{
					this.OnTên_SP_KMChanging(value);
					this.SendPropertyChanging();
					this._Tên_SP_KM = value;
					this.SendPropertyChanged("Tên_SP_KM");
					this.OnTên_SP_KMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tỷ lệ CTKM]", Storage="_Tỷ_lệ_CTKM", DbType="Float")]
		public System.Nullable<double> Tỷ_lệ_CTKM
		{
			get
			{
				return this._Tỷ_lệ_CTKM;
			}
			set
			{
				if ((this._Tỷ_lệ_CTKM != value))
				{
					this.OnTỷ_lệ_CTKMChanging(value);
					this.SendPropertyChanging();
					this._Tỷ_lệ_CTKM = value;
					this.SendPropertyChanged("Tỷ_lệ_CTKM");
					this.OnTỷ_lệ_CTKMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Từ ngày]", Storage="_Từ_ngày", DbType="DateTime")]
		public System.Nullable<System.DateTime> Từ_ngày
		{
			get
			{
				return this._Từ_ngày;
			}
			set
			{
				if ((this._Từ_ngày != value))
				{
					this.OnTừ_ngàyChanging(value);
					this.SendPropertyChanging();
					this._Từ_ngày = value;
					this.SendPropertyChanged("Từ_ngày");
					this.OnTừ_ngàyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Đến Ngày]", Storage="_Đến_Ngày", DbType="DateTime")]
		public System.Nullable<System.DateTime> Đến_Ngày
		{
			get
			{
				return this._Đến_Ngày;
			}
			set
			{
				if ((this._Đến_Ngày != value))
				{
					this.OnĐến_NgàyChanging(value);
					this.SendPropertyChanging();
					this._Đến_Ngày = value;
					this.SendPropertyChanged("Đến_Ngày");
					this.OnĐến_NgàyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nhóm khách hàng]", Storage="_Nhóm_khách_hàng", DbType="NVarChar(255)")]
		public string Nhóm_khách_hàng
		{
			get
			{
				return this._Nhóm_khách_hàng;
			}
			set
			{
				if ((this._Nhóm_khách_hàng != value))
				{
					this.OnNhóm_khách_hàngChanging(value);
					this.SendPropertyChanging();
					this._Nhóm_khách_hàng = value;
					this.SendPropertyChanged("Nhóm_khách_hàng");
					this.OnNhóm_khách_hàngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enduser", DbType="NVarChar(255)")]
		public string enduser
		{
			get
			{
				return this._enduser;
			}
			set
			{
				if ((this._enduser != value))
				{
					this.OnenduserChanging(value);
					this.SendPropertyChanging();
					this._enduser = value;
					this.SendPropertyChanged("enduser");
					this.OnenduserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Temp")]
	public partial class tbl_Temp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _Version;
		
		private string _server;
		
		private string _username;
		
		private string _password;
		
		private string _signoffby;
		
		private string _possition;
		
		private string _phonecontact;
		
		private System.Nullable<int> _siteid;
		
		private string _note;
		
		private string _contactperson;
		
		private string _nameofbarnch;
		
		private string _addressofbarnch;
		
		private bool _DeleteData;
		
		private bool _EditServerData;
		
		private bool _Depositintput;
		
		private bool _EditReportsaffter;
		
		private bool _InputDepositInpass;
		
		private bool _PriodMake;
		
		private bool _Systemconfig;
		
		private bool _uploadBeginbalance;
		
		private bool _endyearPackdata;
		
		private bool _makedepostfromadjamount;
		
		private bool _deductdepositamount;
		
		private bool _redoInputviry;
		
		private bool _uploadpriviousPriod;
		
		private System.Data.Linq.Binary _imagesign;
		
		private bool _nationKA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnVersionChanging(System.Nullable<int> value);
    partial void OnVersionChanged();
    partial void OnserverChanging(string value);
    partial void OnserverChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnsignoffbyChanging(string value);
    partial void OnsignoffbyChanged();
    partial void OnpossitionChanging(string value);
    partial void OnpossitionChanged();
    partial void OnphonecontactChanging(string value);
    partial void OnphonecontactChanged();
    partial void OnsiteidChanging(System.Nullable<int> value);
    partial void OnsiteidChanged();
    partial void OnnoteChanging(string value);
    partial void OnnoteChanged();
    partial void OncontactpersonChanging(string value);
    partial void OncontactpersonChanged();
    partial void OnnameofbarnchChanging(string value);
    partial void OnnameofbarnchChanged();
    partial void OnaddressofbarnchChanging(string value);
    partial void OnaddressofbarnchChanged();
    partial void OnDeleteDataChanging(bool value);
    partial void OnDeleteDataChanged();
    partial void OnEditServerDataChanging(bool value);
    partial void OnEditServerDataChanged();
    partial void OnDepositintputChanging(bool value);
    partial void OnDepositintputChanged();
    partial void OnEditReportsaffterChanging(bool value);
    partial void OnEditReportsaffterChanged();
    partial void OnInputDepositInpassChanging(bool value);
    partial void OnInputDepositInpassChanged();
    partial void OnPriodMakeChanging(bool value);
    partial void OnPriodMakeChanged();
    partial void OnSystemconfigChanging(bool value);
    partial void OnSystemconfigChanged();
    partial void OnuploadBeginbalanceChanging(bool value);
    partial void OnuploadBeginbalanceChanged();
    partial void OnendyearPackdataChanging(bool value);
    partial void OnendyearPackdataChanged();
    partial void OnmakedepostfromadjamountChanging(bool value);
    partial void OnmakedepostfromadjamountChanged();
    partial void OndeductdepositamountChanging(bool value);
    partial void OndeductdepositamountChanged();
    partial void OnredoInputviryChanging(bool value);
    partial void OnredoInputviryChanged();
    partial void OnuploadpriviousPriodChanging(bool value);
    partial void OnuploadpriviousPriodChanged();
    partial void OnimagesignChanging(System.Data.Linq.Binary value);
    partial void OnimagesignChanged();
    partial void OnnationKAChanging(bool value);
    partial void OnnationKAChanged();
    #endregion
		
		public tbl_Temp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="Int")]
		public System.Nullable<int> Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this.OnVersionChanging(value);
					this.SendPropertyChanging();
					this._Version = value;
					this.SendPropertyChanged("Version");
					this.OnVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_server", DbType="NChar(225)")]
		public string server
		{
			get
			{
				return this._server;
			}
			set
			{
				if ((this._server != value))
				{
					this.OnserverChanging(value);
					this.SendPropertyChanging();
					this._server = value;
					this.SendPropertyChanged("server");
					this.OnserverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NChar(225)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NChar(225)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_signoffby", DbType="NChar(225)")]
		public string signoffby
		{
			get
			{
				return this._signoffby;
			}
			set
			{
				if ((this._signoffby != value))
				{
					this.OnsignoffbyChanging(value);
					this.SendPropertyChanging();
					this._signoffby = value;
					this.SendPropertyChanged("signoffby");
					this.OnsignoffbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_possition", DbType="NChar(225)")]
		public string possition
		{
			get
			{
				return this._possition;
			}
			set
			{
				if ((this._possition != value))
				{
					this.OnpossitionChanging(value);
					this.SendPropertyChanging();
					this._possition = value;
					this.SendPropertyChanged("possition");
					this.OnpossitionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phonecontact", DbType="NChar(225)")]
		public string phonecontact
		{
			get
			{
				return this._phonecontact;
			}
			set
			{
				if ((this._phonecontact != value))
				{
					this.OnphonecontactChanging(value);
					this.SendPropertyChanging();
					this._phonecontact = value;
					this.SendPropertyChanged("phonecontact");
					this.OnphonecontactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteid", DbType="Int")]
		public System.Nullable<int> siteid
		{
			get
			{
				return this._siteid;
			}
			set
			{
				if ((this._siteid != value))
				{
					this.OnsiteidChanging(value);
					this.SendPropertyChanging();
					this._siteid = value;
					this.SendPropertyChanged("siteid");
					this.OnsiteidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_note", DbType="NChar(225)")]
		public string note
		{
			get
			{
				return this._note;
			}
			set
			{
				if ((this._note != value))
				{
					this.OnnoteChanging(value);
					this.SendPropertyChanging();
					this._note = value;
					this.SendPropertyChanged("note");
					this.OnnoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactperson", DbType="NChar(225)")]
		public string contactperson
		{
			get
			{
				return this._contactperson;
			}
			set
			{
				if ((this._contactperson != value))
				{
					this.OncontactpersonChanging(value);
					this.SendPropertyChanging();
					this._contactperson = value;
					this.SendPropertyChanged("contactperson");
					this.OncontactpersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameofbarnch", DbType="NChar(225)")]
		public string nameofbarnch
		{
			get
			{
				return this._nameofbarnch;
			}
			set
			{
				if ((this._nameofbarnch != value))
				{
					this.OnnameofbarnchChanging(value);
					this.SendPropertyChanging();
					this._nameofbarnch = value;
					this.SendPropertyChanged("nameofbarnch");
					this.OnnameofbarnchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addressofbarnch", DbType="NChar(225)")]
		public string addressofbarnch
		{
			get
			{
				return this._addressofbarnch;
			}
			set
			{
				if ((this._addressofbarnch != value))
				{
					this.OnaddressofbarnchChanging(value);
					this.SendPropertyChanging();
					this._addressofbarnch = value;
					this.SendPropertyChanged("addressofbarnch");
					this.OnaddressofbarnchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteData", DbType="Bit NOT NULL")]
		public bool DeleteData
		{
			get
			{
				return this._DeleteData;
			}
			set
			{
				if ((this._DeleteData != value))
				{
					this.OnDeleteDataChanging(value);
					this.SendPropertyChanging();
					this._DeleteData = value;
					this.SendPropertyChanged("DeleteData");
					this.OnDeleteDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditServerData", DbType="Bit NOT NULL")]
		public bool EditServerData
		{
			get
			{
				return this._EditServerData;
			}
			set
			{
				if ((this._EditServerData != value))
				{
					this.OnEditServerDataChanging(value);
					this.SendPropertyChanging();
					this._EditServerData = value;
					this.SendPropertyChanged("EditServerData");
					this.OnEditServerDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Depositintput", DbType="Bit NOT NULL")]
		public bool Depositintput
		{
			get
			{
				return this._Depositintput;
			}
			set
			{
				if ((this._Depositintput != value))
				{
					this.OnDepositintputChanging(value);
					this.SendPropertyChanging();
					this._Depositintput = value;
					this.SendPropertyChanged("Depositintput");
					this.OnDepositintputChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditReportsaffter", DbType="Bit NOT NULL")]
		public bool EditReportsaffter
		{
			get
			{
				return this._EditReportsaffter;
			}
			set
			{
				if ((this._EditReportsaffter != value))
				{
					this.OnEditReportsaffterChanging(value);
					this.SendPropertyChanging();
					this._EditReportsaffter = value;
					this.SendPropertyChanged("EditReportsaffter");
					this.OnEditReportsaffterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InputDepositInpass", DbType="Bit NOT NULL")]
		public bool InputDepositInpass
		{
			get
			{
				return this._InputDepositInpass;
			}
			set
			{
				if ((this._InputDepositInpass != value))
				{
					this.OnInputDepositInpassChanging(value);
					this.SendPropertyChanging();
					this._InputDepositInpass = value;
					this.SendPropertyChanged("InputDepositInpass");
					this.OnInputDepositInpassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriodMake", DbType="Bit NOT NULL")]
		public bool PriodMake
		{
			get
			{
				return this._PriodMake;
			}
			set
			{
				if ((this._PriodMake != value))
				{
					this.OnPriodMakeChanging(value);
					this.SendPropertyChanging();
					this._PriodMake = value;
					this.SendPropertyChanged("PriodMake");
					this.OnPriodMakeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Systemconfig", DbType="Bit NOT NULL")]
		public bool Systemconfig
		{
			get
			{
				return this._Systemconfig;
			}
			set
			{
				if ((this._Systemconfig != value))
				{
					this.OnSystemconfigChanging(value);
					this.SendPropertyChanging();
					this._Systemconfig = value;
					this.SendPropertyChanged("Systemconfig");
					this.OnSystemconfigChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uploadBeginbalance", DbType="Bit NOT NULL")]
		public bool uploadBeginbalance
		{
			get
			{
				return this._uploadBeginbalance;
			}
			set
			{
				if ((this._uploadBeginbalance != value))
				{
					this.OnuploadBeginbalanceChanging(value);
					this.SendPropertyChanging();
					this._uploadBeginbalance = value;
					this.SendPropertyChanged("uploadBeginbalance");
					this.OnuploadBeginbalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endyearPackdata", DbType="Bit NOT NULL")]
		public bool endyearPackdata
		{
			get
			{
				return this._endyearPackdata;
			}
			set
			{
				if ((this._endyearPackdata != value))
				{
					this.OnendyearPackdataChanging(value);
					this.SendPropertyChanging();
					this._endyearPackdata = value;
					this.SendPropertyChanged("endyearPackdata");
					this.OnendyearPackdataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makedepostfromadjamount", DbType="Bit NOT NULL")]
		public bool makedepostfromadjamount
		{
			get
			{
				return this._makedepostfromadjamount;
			}
			set
			{
				if ((this._makedepostfromadjamount != value))
				{
					this.OnmakedepostfromadjamountChanging(value);
					this.SendPropertyChanging();
					this._makedepostfromadjamount = value;
					this.SendPropertyChanged("makedepostfromadjamount");
					this.OnmakedepostfromadjamountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deductdepositamount", DbType="Bit NOT NULL")]
		public bool deductdepositamount
		{
			get
			{
				return this._deductdepositamount;
			}
			set
			{
				if ((this._deductdepositamount != value))
				{
					this.OndeductdepositamountChanging(value);
					this.SendPropertyChanging();
					this._deductdepositamount = value;
					this.SendPropertyChanged("deductdepositamount");
					this.OndeductdepositamountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_redoInputviry", DbType="Bit NOT NULL")]
		public bool redoInputviry
		{
			get
			{
				return this._redoInputviry;
			}
			set
			{
				if ((this._redoInputviry != value))
				{
					this.OnredoInputviryChanging(value);
					this.SendPropertyChanging();
					this._redoInputviry = value;
					this.SendPropertyChanged("redoInputviry");
					this.OnredoInputviryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uploadpriviousPriod", DbType="Bit NOT NULL")]
		public bool uploadpriviousPriod
		{
			get
			{
				return this._uploadpriviousPriod;
			}
			set
			{
				if ((this._uploadpriviousPriod != value))
				{
					this.OnuploadpriviousPriodChanging(value);
					this.SendPropertyChanging();
					this._uploadpriviousPriod = value;
					this.SendPropertyChanged("uploadpriviousPriod");
					this.OnuploadpriviousPriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagesign", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary imagesign
		{
			get
			{
				return this._imagesign;
			}
			set
			{
				if ((this._imagesign != value))
				{
					this.OnimagesignChanging(value);
					this.SendPropertyChanging();
					this._imagesign = value;
					this.SendPropertyChanged("imagesign");
					this.OnimagesignChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nationKA", DbType="Bit NOT NULL")]
		public bool nationKA
		{
			get
			{
				return this._nationKA;
			}
			set
			{
				if ((this._nationKA != value))
				{
					this.OnnationKAChanging(value);
					this.SendPropertyChanging();
					this._nationKA = value;
					this.SendPropertyChanged("nationKA");
					this.OnnationKAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_NhomKHKM")]
	public partial class tbl_NhomKHKM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mã_nhóm_KH;
		
		private string _CodeKH;
		
		private int _id;
		
		private string _enduser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMã_nhóm_KHChanging(string value);
    partial void OnMã_nhóm_KHChanged();
    partial void OnCodeKHChanging(string value);
    partial void OnCodeKHChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnenduserChanging(string value);
    partial void OnenduserChanged();
    #endregion
		
		public tbl_NhomKHKM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mã_nhóm_KH", DbType="NVarChar(30)")]
		public string Mã_nhóm_KH
		{
			get
			{
				return this._Mã_nhóm_KH;
			}
			set
			{
				if ((this._Mã_nhóm_KH != value))
				{
					this.OnMã_nhóm_KHChanging(value);
					this.SendPropertyChanging();
					this._Mã_nhóm_KH = value;
					this.SendPropertyChanged("Mã_nhóm_KH");
					this.OnMã_nhóm_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeKH", DbType="NVarChar(30)")]
		public string CodeKH
		{
			get
			{
				return this._CodeKH;
			}
			set
			{
				if ((this._CodeKH != value))
				{
					this.OnCodeKHChanging(value);
					this.SendPropertyChanging();
					this._CodeKH = value;
					this.SendPropertyChanged("CodeKH");
					this.OnCodeKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enduser", DbType="NVarChar(225)")]
		public string enduser
		{
			get
			{
				return this._enduser;
			}
			set
			{
				if ((this._enduser != value))
				{
					this.OnenduserChanging(value);
					this.SendPropertyChanging();
					this._enduser = value;
					this.SendPropertyChanged("enduser");
					this.OnenduserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Product")]
	public partial class tbl_Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Marterial_code;
		
		private string _Marterial_name;
		
		private string _Pack_size;
		
		private System.Nullable<double> _PC_Quy_chuan;
		
		private System.Nullable<double> _UC_Rate;
		
		private int _id;
		
		private string _enduser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMarterial_codeChanging(string value);
    partial void OnMarterial_codeChanged();
    partial void OnMarterial_nameChanging(string value);
    partial void OnMarterial_nameChanged();
    partial void OnPack_sizeChanging(string value);
    partial void OnPack_sizeChanged();
    partial void OnPC_Quy_chuanChanging(System.Nullable<double> value);
    partial void OnPC_Quy_chuanChanged();
    partial void OnUC_RateChanging(System.Nullable<double> value);
    partial void OnUC_RateChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnenduserChanging(string value);
    partial void OnenduserChanged();
    #endregion
		
		public tbl_Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Marterial code]", Storage="_Marterial_code", DbType="NVarChar(255)")]
		public string Marterial_code
		{
			get
			{
				return this._Marterial_code;
			}
			set
			{
				if ((this._Marterial_code != value))
				{
					this.OnMarterial_codeChanging(value);
					this.SendPropertyChanging();
					this._Marterial_code = value;
					this.SendPropertyChanged("Marterial_code");
					this.OnMarterial_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Marterial name]", Storage="_Marterial_name", DbType="NVarChar(255)")]
		public string Marterial_name
		{
			get
			{
				return this._Marterial_name;
			}
			set
			{
				if ((this._Marterial_name != value))
				{
					this.OnMarterial_nameChanging(value);
					this.SendPropertyChanging();
					this._Marterial_name = value;
					this.SendPropertyChanged("Marterial_name");
					this.OnMarterial_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Pack size]", Storage="_Pack_size", DbType="NVarChar(255)")]
		public string Pack_size
		{
			get
			{
				return this._Pack_size;
			}
			set
			{
				if ((this._Pack_size != value))
				{
					this.OnPack_sizeChanging(value);
					this.SendPropertyChanging();
					this._Pack_size = value;
					this.SendPropertyChanged("Pack_size");
					this.OnPack_sizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PC Quy chuan]", Storage="_PC_Quy_chuan", DbType="Float")]
		public System.Nullable<double> PC_Quy_chuan
		{
			get
			{
				return this._PC_Quy_chuan;
			}
			set
			{
				if ((this._PC_Quy_chuan != value))
				{
					this.OnPC_Quy_chuanChanging(value);
					this.SendPropertyChanging();
					this._PC_Quy_chuan = value;
					this.SendPropertyChanged("PC_Quy_chuan");
					this.OnPC_Quy_chuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[UC Rate]", Storage="_UC_Rate", DbType="Float")]
		public System.Nullable<double> UC_Rate
		{
			get
			{
				return this._UC_Rate;
			}
			set
			{
				if ((this._UC_Rate != value))
				{
					this.OnUC_RateChanging(value);
					this.SendPropertyChanging();
					this._UC_Rate = value;
					this.SendPropertyChanged("UC_Rate");
					this.OnUC_RateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enduser", DbType="NVarChar(255)")]
		public string enduser
		{
			get
			{
				return this._enduser;
			}
			set
			{
				if ((this._enduser != value))
				{
					this.OnenduserChanging(value);
					this.SendPropertyChanging();
					this._enduser = value;
					this.SendPropertyChanged("enduser");
					this.OnenduserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_rptnotEnought")]
	public partial class tbl_rptnotEnought : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Created;
		
		private string _Material;
		
		private System.Nullable<double> _Quantytibuy;
		
		private System.Nullable<double> _Quantityfree;
		
		private System.Nullable<double> _FreeclasesPaid;
		
		private bool _filter;
		
		private string _enduser;
		
		private int _id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCreatedChanging(string value);
    partial void OnCreatedChanged();
    partial void OnMaterialChanging(string value);
    partial void OnMaterialChanged();
    partial void OnQuantytibuyChanging(System.Nullable<double> value);
    partial void OnQuantytibuyChanged();
    partial void OnQuantityfreeChanging(System.Nullable<double> value);
    partial void OnQuantityfreeChanged();
    partial void OnFreeclasesPaidChanging(System.Nullable<double> value);
    partial void OnFreeclasesPaidChanged();
    partial void OnfilterChanging(bool value);
    partial void OnfilterChanged();
    partial void OnenduserChanging(string value);
    partial void OnenduserChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    #endregion
		
		public tbl_rptnotEnought()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="NVarChar(255)")]
		public string Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Material", DbType="NVarChar(255)")]
		public string Material
		{
			get
			{
				return this._Material;
			}
			set
			{
				if ((this._Material != value))
				{
					this.OnMaterialChanging(value);
					this.SendPropertyChanging();
					this._Material = value;
					this.SendPropertyChanged("Material");
					this.OnMaterialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantytibuy", DbType="Float")]
		public System.Nullable<double> Quantytibuy
		{
			get
			{
				return this._Quantytibuy;
			}
			set
			{
				if ((this._Quantytibuy != value))
				{
					this.OnQuantytibuyChanging(value);
					this.SendPropertyChanging();
					this._Quantytibuy = value;
					this.SendPropertyChanged("Quantytibuy");
					this.OnQuantytibuyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantityfree", DbType="Float")]
		public System.Nullable<double> Quantityfree
		{
			get
			{
				return this._Quantityfree;
			}
			set
			{
				if ((this._Quantityfree != value))
				{
					this.OnQuantityfreeChanging(value);
					this.SendPropertyChanging();
					this._Quantityfree = value;
					this.SendPropertyChanged("Quantityfree");
					this.OnQuantityfreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FreeclasesPaid", DbType="Float")]
		public System.Nullable<double> FreeclasesPaid
		{
			get
			{
				return this._FreeclasesPaid;
			}
			set
			{
				if ((this._FreeclasesPaid != value))
				{
					this.OnFreeclasesPaidChanging(value);
					this.SendPropertyChanging();
					this._FreeclasesPaid = value;
					this.SendPropertyChanged("FreeclasesPaid");
					this.OnFreeclasesPaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filter", DbType="Bit NOT NULL")]
		public bool filter
		{
			get
			{
				return this._filter;
			}
			set
			{
				if ((this._filter != value))
				{
					this.OnfilterChanging(value);
					this.SendPropertyChanging();
					this._filter = value;
					this.SendPropertyChanged("filter");
					this.OnfilterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enduser", DbType="NVarChar(255)")]
		public string enduser
		{
			get
			{
				return this._enduser;
			}
			set
			{
				if ((this._enduser != value))
				{
					this.OnenduserChanging(value);
					this.SendPropertyChanging();
					this._enduser = value;
					this.SendPropertyChanged("enduser");
					this.OnenduserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_SalesFreehavetopaid")]
	public partial class tbl_SalesFreehavetopaid : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<double> _Order_Number;
		
		private string _ma_CTKM;
		
		private string _Material;
		
		private string _Description;
		
		private System.Nullable<double> _EstimateFree_quantity;
		
		private int _id;
		
		private string _enduser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOrder_NumberChanging(System.Nullable<double> value);
    partial void OnOrder_NumberChanged();
    partial void Onma_CTKMChanging(string value);
    partial void Onma_CTKMChanged();
    partial void OnMaterialChanging(string value);
    partial void OnMaterialChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnEstimateFree_quantityChanging(System.Nullable<double> value);
    partial void OnEstimateFree_quantityChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnenduserChanging(string value);
    partial void OnenduserChanged();
    #endregion
		
		public tbl_SalesFreehavetopaid()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Order_Number", DbType="Float")]
		public System.Nullable<double> Order_Number
		{
			get
			{
				return this._Order_Number;
			}
			set
			{
				if ((this._Order_Number != value))
				{
					this.OnOrder_NumberChanging(value);
					this.SendPropertyChanging();
					this._Order_Number = value;
					this.SendPropertyChanged("Order_Number");
					this.OnOrder_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_CTKM", DbType="NVarChar(255)")]
		public string ma_CTKM
		{
			get
			{
				return this._ma_CTKM;
			}
			set
			{
				if ((this._ma_CTKM != value))
				{
					this.Onma_CTKMChanging(value);
					this.SendPropertyChanging();
					this._ma_CTKM = value;
					this.SendPropertyChanged("ma_CTKM");
					this.Onma_CTKMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Material", DbType="NVarChar(255)")]
		public string Material
		{
			get
			{
				return this._Material;
			}
			set
			{
				if ((this._Material != value))
				{
					this.OnMaterialChanging(value);
					this.SendPropertyChanging();
					this._Material = value;
					this.SendPropertyChanged("Material");
					this.OnMaterialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(255)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstimateFree_quantity", DbType="Float")]
		public System.Nullable<double> EstimateFree_quantity
		{
			get
			{
				return this._EstimateFree_quantity;
			}
			set
			{
				if ((this._EstimateFree_quantity != value))
				{
					this.OnEstimateFree_quantityChanging(value);
					this.SendPropertyChanging();
					this._EstimateFree_quantity = value;
					this.SendPropertyChanged("EstimateFree_quantity");
					this.OnEstimateFree_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enduser", DbType="NVarChar(255)")]
		public string enduser
		{
			get
			{
				return this._enduser;
			}
			set
			{
				if ((this._enduser != value))
				{
					this.OnenduserChanging(value);
					this.SendPropertyChanging();
					this._enduser = value;
					this.SendPropertyChanged("enduser");
					this.OnenduserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_SalesFreeOrder")]
	public partial class tbl_SalesFreeOrder : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Created;
		
		private string _SOrg;
		
		private string _PO_number;
		
		private System.Nullable<System.DateTime> _Doc_Date;
		
		private System.Nullable<System.DateTime> _Dlv_Date;
		
		private string _New_PO_number;
		
		private System.Nullable<double> _Order_Number;
		
		private System.Nullable<double> _Sold_to_party;
		
		private string _Name;
		
		private string _Material;
		
		private string _Description;
		
		private System.Nullable<double> _Order_quantity;
		
		private System.Nullable<double> _ConfirmQty;
		
		private string _Status;
		
		private System.Nullable<double> _Item;
		
		private System.Nullable<double> _Net_price;
		
		private string _Rj;
		
		private string _Plnt;
		
		private System.Nullable<double> _Net_value;
		
		private int _id;
		
		private System.Nullable<double> _byOrder;
		
		private bool _rptselect;
		
		private string _ma_CTKM;
		
		private string _enduser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCreatedChanging(string value);
    partial void OnCreatedChanged();
    partial void OnSOrgChanging(string value);
    partial void OnSOrgChanged();
    partial void OnPO_numberChanging(string value);
    partial void OnPO_numberChanged();
    partial void OnDoc_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnDoc_DateChanged();
    partial void OnDlv_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnDlv_DateChanged();
    partial void OnNew_PO_numberChanging(string value);
    partial void OnNew_PO_numberChanged();
    partial void OnOrder_NumberChanging(System.Nullable<double> value);
    partial void OnOrder_NumberChanged();
    partial void OnSold_to_partyChanging(System.Nullable<double> value);
    partial void OnSold_to_partyChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnMaterialChanging(string value);
    partial void OnMaterialChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnOrder_quantityChanging(System.Nullable<double> value);
    partial void OnOrder_quantityChanged();
    partial void OnConfirmQtyChanging(System.Nullable<double> value);
    partial void OnConfirmQtyChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnItemChanging(System.Nullable<double> value);
    partial void OnItemChanged();
    partial void OnNet_priceChanging(System.Nullable<double> value);
    partial void OnNet_priceChanged();
    partial void OnRjChanging(string value);
    partial void OnRjChanged();
    partial void OnPlntChanging(string value);
    partial void OnPlntChanged();
    partial void OnNet_valueChanging(System.Nullable<double> value);
    partial void OnNet_valueChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnbyOrderChanging(System.Nullable<double> value);
    partial void OnbyOrderChanged();
    partial void OnrptselectChanging(bool value);
    partial void OnrptselectChanged();
    partial void Onma_CTKMChanging(string value);
    partial void Onma_CTKMChanged();
    partial void OnenduserChanging(string value);
    partial void OnenduserChanged();
    #endregion
		
		public tbl_SalesFreeOrder()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="NVarChar(255)")]
		public string Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOrg", DbType="NVarChar(255)")]
		public string SOrg
		{
			get
			{
				return this._SOrg;
			}
			set
			{
				if ((this._SOrg != value))
				{
					this.OnSOrgChanging(value);
					this.SendPropertyChanging();
					this._SOrg = value;
					this.SendPropertyChanged("SOrg");
					this.OnSOrgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PO_number", DbType="NVarChar(255)")]
		public string PO_number
		{
			get
			{
				return this._PO_number;
			}
			set
			{
				if ((this._PO_number != value))
				{
					this.OnPO_numberChanging(value);
					this.SendPropertyChanging();
					this._PO_number = value;
					this.SendPropertyChanged("PO_number");
					this.OnPO_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doc_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Doc_Date
		{
			get
			{
				return this._Doc_Date;
			}
			set
			{
				if ((this._Doc_Date != value))
				{
					this.OnDoc_DateChanging(value);
					this.SendPropertyChanging();
					this._Doc_Date = value;
					this.SendPropertyChanged("Doc_Date");
					this.OnDoc_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dlv_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Dlv_Date
		{
			get
			{
				return this._Dlv_Date;
			}
			set
			{
				if ((this._Dlv_Date != value))
				{
					this.OnDlv_DateChanging(value);
					this.SendPropertyChanging();
					this._Dlv_Date = value;
					this.SendPropertyChanged("Dlv_Date");
					this.OnDlv_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_New_PO_number", DbType="NVarChar(255)")]
		public string New_PO_number
		{
			get
			{
				return this._New_PO_number;
			}
			set
			{
				if ((this._New_PO_number != value))
				{
					this.OnNew_PO_numberChanging(value);
					this.SendPropertyChanging();
					this._New_PO_number = value;
					this.SendPropertyChanged("New_PO_number");
					this.OnNew_PO_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Order_Number", DbType="Float")]
		public System.Nullable<double> Order_Number
		{
			get
			{
				return this._Order_Number;
			}
			set
			{
				if ((this._Order_Number != value))
				{
					this.OnOrder_NumberChanging(value);
					this.SendPropertyChanging();
					this._Order_Number = value;
					this.SendPropertyChanged("Order_Number");
					this.OnOrder_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sold_to_party", DbType="Float")]
		public System.Nullable<double> Sold_to_party
		{
			get
			{
				return this._Sold_to_party;
			}
			set
			{
				if ((this._Sold_to_party != value))
				{
					this.OnSold_to_partyChanging(value);
					this.SendPropertyChanging();
					this._Sold_to_party = value;
					this.SendPropertyChanged("Sold_to_party");
					this.OnSold_to_partyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Material", DbType="NVarChar(255)")]
		public string Material
		{
			get
			{
				return this._Material;
			}
			set
			{
				if ((this._Material != value))
				{
					this.OnMaterialChanging(value);
					this.SendPropertyChanging();
					this._Material = value;
					this.SendPropertyChanged("Material");
					this.OnMaterialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(255)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Order_quantity", DbType="Float")]
		public System.Nullable<double> Order_quantity
		{
			get
			{
				return this._Order_quantity;
			}
			set
			{
				if ((this._Order_quantity != value))
				{
					this.OnOrder_quantityChanging(value);
					this.SendPropertyChanging();
					this._Order_quantity = value;
					this.SendPropertyChanged("Order_quantity");
					this.OnOrder_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmQty", DbType="Float")]
		public System.Nullable<double> ConfirmQty
		{
			get
			{
				return this._ConfirmQty;
			}
			set
			{
				if ((this._ConfirmQty != value))
				{
					this.OnConfirmQtyChanging(value);
					this.SendPropertyChanging();
					this._ConfirmQty = value;
					this.SendPropertyChanged("ConfirmQty");
					this.OnConfirmQtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(255)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item", DbType="Float")]
		public System.Nullable<double> Item
		{
			get
			{
				return this._Item;
			}
			set
			{
				if ((this._Item != value))
				{
					this.OnItemChanging(value);
					this.SendPropertyChanging();
					this._Item = value;
					this.SendPropertyChanged("Item");
					this.OnItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Net_price", DbType="Float")]
		public System.Nullable<double> Net_price
		{
			get
			{
				return this._Net_price;
			}
			set
			{
				if ((this._Net_price != value))
				{
					this.OnNet_priceChanging(value);
					this.SendPropertyChanging();
					this._Net_price = value;
					this.SendPropertyChanged("Net_price");
					this.OnNet_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rj", DbType="NVarChar(255)")]
		public string Rj
		{
			get
			{
				return this._Rj;
			}
			set
			{
				if ((this._Rj != value))
				{
					this.OnRjChanging(value);
					this.SendPropertyChanging();
					this._Rj = value;
					this.SendPropertyChanged("Rj");
					this.OnRjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Plnt", DbType="NVarChar(255)")]
		public string Plnt
		{
			get
			{
				return this._Plnt;
			}
			set
			{
				if ((this._Plnt != value))
				{
					this.OnPlntChanging(value);
					this.SendPropertyChanging();
					this._Plnt = value;
					this.SendPropertyChanged("Plnt");
					this.OnPlntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Net_value", DbType="Float")]
		public System.Nullable<double> Net_value
		{
			get
			{
				return this._Net_value;
			}
			set
			{
				if ((this._Net_value != value))
				{
					this.OnNet_valueChanging(value);
					this.SendPropertyChanging();
					this._Net_value = value;
					this.SendPropertyChanged("Net_value");
					this.OnNet_valueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_byOrder", DbType="Float")]
		public System.Nullable<double> byOrder
		{
			get
			{
				return this._byOrder;
			}
			set
			{
				if ((this._byOrder != value))
				{
					this.OnbyOrderChanging(value);
					this.SendPropertyChanging();
					this._byOrder = value;
					this.SendPropertyChanged("byOrder");
					this.OnbyOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rptselect", DbType="Bit NOT NULL")]
		public bool rptselect
		{
			get
			{
				return this._rptselect;
			}
			set
			{
				if ((this._rptselect != value))
				{
					this.OnrptselectChanging(value);
					this.SendPropertyChanging();
					this._rptselect = value;
					this.SendPropertyChanged("rptselect");
					this.OnrptselectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_CTKM", DbType="NVarChar(255)")]
		public string ma_CTKM
		{
			get
			{
				return this._ma_CTKM;
			}
			set
			{
				if ((this._ma_CTKM != value))
				{
					this.Onma_CTKMChanging(value);
					this.SendPropertyChanging();
					this._ma_CTKM = value;
					this.SendPropertyChanged("ma_CTKM");
					this.Onma_CTKMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enduser", DbType="NVarChar(255)")]
		public string enduser
		{
			get
			{
				return this._enduser;
			}
			set
			{
				if ((this._enduser != value))
				{
					this.OnenduserChanging(value);
					this.SendPropertyChanging();
					this._enduser = value;
					this.SendPropertyChanged("enduser");
					this.OnenduserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Salesorder")]
	public partial class tbl_Salesorder : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Created;
		
		private string _SOrg;
		
		private string _PO_number;
		
		private string _Doc_Date;
		
		private string _Dlv_Date;
		
		private System.Nullable<double> _Order_Number;
		
		private System.Nullable<double> _Sold_to_party;
		
		private string _Name;
		
		private string _Material;
		
		private string _Description;
		
		private System.Nullable<double> _Order_quantity;
		
		private System.Nullable<double> _ConfirmQty;
		
		private string _Status;
		
		private System.Nullable<double> _Item;
		
		private System.Nullable<double> _Net_price;
		
		private string _Rj;
		
		private string _Plnt;
		
		private System.Nullable<double> _Net_value;
		
		private int _id;
		
		private bool _selectprt;
		
		private string _enduser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCreatedChanging(string value);
    partial void OnCreatedChanged();
    partial void OnSOrgChanging(string value);
    partial void OnSOrgChanged();
    partial void OnPO_numberChanging(string value);
    partial void OnPO_numberChanged();
    partial void OnDoc_DateChanging(string value);
    partial void OnDoc_DateChanged();
    partial void OnDlv_DateChanging(string value);
    partial void OnDlv_DateChanged();
    partial void OnOrder_NumberChanging(System.Nullable<double> value);
    partial void OnOrder_NumberChanged();
    partial void OnSold_to_partyChanging(System.Nullable<double> value);
    partial void OnSold_to_partyChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnMaterialChanging(string value);
    partial void OnMaterialChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnOrder_quantityChanging(System.Nullable<double> value);
    partial void OnOrder_quantityChanged();
    partial void OnConfirmQtyChanging(System.Nullable<double> value);
    partial void OnConfirmQtyChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnItemChanging(System.Nullable<double> value);
    partial void OnItemChanged();
    partial void OnNet_priceChanging(System.Nullable<double> value);
    partial void OnNet_priceChanged();
    partial void OnRjChanging(string value);
    partial void OnRjChanged();
    partial void OnPlntChanging(string value);
    partial void OnPlntChanged();
    partial void OnNet_valueChanging(System.Nullable<double> value);
    partial void OnNet_valueChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnselectprtChanging(bool value);
    partial void OnselectprtChanged();
    partial void OnenduserChanging(string value);
    partial void OnenduserChanged();
    #endregion
		
		public tbl_Salesorder()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="NVarChar(255)")]
		public string Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOrg", DbType="NVarChar(255)")]
		public string SOrg
		{
			get
			{
				return this._SOrg;
			}
			set
			{
				if ((this._SOrg != value))
				{
					this.OnSOrgChanging(value);
					this.SendPropertyChanging();
					this._SOrg = value;
					this.SendPropertyChanged("SOrg");
					this.OnSOrgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PO_number", DbType="NVarChar(255)")]
		public string PO_number
		{
			get
			{
				return this._PO_number;
			}
			set
			{
				if ((this._PO_number != value))
				{
					this.OnPO_numberChanging(value);
					this.SendPropertyChanging();
					this._PO_number = value;
					this.SendPropertyChanged("PO_number");
					this.OnPO_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doc_Date", DbType="NVarChar(255)")]
		public string Doc_Date
		{
			get
			{
				return this._Doc_Date;
			}
			set
			{
				if ((this._Doc_Date != value))
				{
					this.OnDoc_DateChanging(value);
					this.SendPropertyChanging();
					this._Doc_Date = value;
					this.SendPropertyChanged("Doc_Date");
					this.OnDoc_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dlv_Date", DbType="NVarChar(255)")]
		public string Dlv_Date
		{
			get
			{
				return this._Dlv_Date;
			}
			set
			{
				if ((this._Dlv_Date != value))
				{
					this.OnDlv_DateChanging(value);
					this.SendPropertyChanging();
					this._Dlv_Date = value;
					this.SendPropertyChanged("Dlv_Date");
					this.OnDlv_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Order_Number", DbType="Float")]
		public System.Nullable<double> Order_Number
		{
			get
			{
				return this._Order_Number;
			}
			set
			{
				if ((this._Order_Number != value))
				{
					this.OnOrder_NumberChanging(value);
					this.SendPropertyChanging();
					this._Order_Number = value;
					this.SendPropertyChanged("Order_Number");
					this.OnOrder_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sold_to_party", DbType="Float")]
		public System.Nullable<double> Sold_to_party
		{
			get
			{
				return this._Sold_to_party;
			}
			set
			{
				if ((this._Sold_to_party != value))
				{
					this.OnSold_to_partyChanging(value);
					this.SendPropertyChanging();
					this._Sold_to_party = value;
					this.SendPropertyChanged("Sold_to_party");
					this.OnSold_to_partyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Material", DbType="NVarChar(255)")]
		public string Material
		{
			get
			{
				return this._Material;
			}
			set
			{
				if ((this._Material != value))
				{
					this.OnMaterialChanging(value);
					this.SendPropertyChanging();
					this._Material = value;
					this.SendPropertyChanged("Material");
					this.OnMaterialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(255)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Order_quantity", DbType="Float")]
		public System.Nullable<double> Order_quantity
		{
			get
			{
				return this._Order_quantity;
			}
			set
			{
				if ((this._Order_quantity != value))
				{
					this.OnOrder_quantityChanging(value);
					this.SendPropertyChanging();
					this._Order_quantity = value;
					this.SendPropertyChanged("Order_quantity");
					this.OnOrder_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmQty", DbType="Float")]
		public System.Nullable<double> ConfirmQty
		{
			get
			{
				return this._ConfirmQty;
			}
			set
			{
				if ((this._ConfirmQty != value))
				{
					this.OnConfirmQtyChanging(value);
					this.SendPropertyChanging();
					this._ConfirmQty = value;
					this.SendPropertyChanged("ConfirmQty");
					this.OnConfirmQtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(255)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item", DbType="Float")]
		public System.Nullable<double> Item
		{
			get
			{
				return this._Item;
			}
			set
			{
				if ((this._Item != value))
				{
					this.OnItemChanging(value);
					this.SendPropertyChanging();
					this._Item = value;
					this.SendPropertyChanged("Item");
					this.OnItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Net_price", DbType="Float")]
		public System.Nullable<double> Net_price
		{
			get
			{
				return this._Net_price;
			}
			set
			{
				if ((this._Net_price != value))
				{
					this.OnNet_priceChanging(value);
					this.SendPropertyChanging();
					this._Net_price = value;
					this.SendPropertyChanged("Net_price");
					this.OnNet_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rj", DbType="NVarChar(255)")]
		public string Rj
		{
			get
			{
				return this._Rj;
			}
			set
			{
				if ((this._Rj != value))
				{
					this.OnRjChanging(value);
					this.SendPropertyChanging();
					this._Rj = value;
					this.SendPropertyChanged("Rj");
					this.OnRjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Plnt", DbType="NVarChar(255)")]
		public string Plnt
		{
			get
			{
				return this._Plnt;
			}
			set
			{
				if ((this._Plnt != value))
				{
					this.OnPlntChanging(value);
					this.SendPropertyChanging();
					this._Plnt = value;
					this.SendPropertyChanged("Plnt");
					this.OnPlntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Net_value", DbType="Float")]
		public System.Nullable<double> Net_value
		{
			get
			{
				return this._Net_value;
			}
			set
			{
				if ((this._Net_value != value))
				{
					this.OnNet_valueChanging(value);
					this.SendPropertyChanging();
					this._Net_value = value;
					this.SendPropertyChanged("Net_value");
					this.OnNet_valueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_selectprt", DbType="Bit NOT NULL")]
		public bool selectprt
		{
			get
			{
				return this._selectprt;
			}
			set
			{
				if ((this._selectprt != value))
				{
					this.OnselectprtChanging(value);
					this.SendPropertyChanging();
					this._selectprt = value;
					this.SendPropertyChanged("selectprt");
					this.OnselectprtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enduser", DbType="NVarChar(255)")]
		public string enduser
		{
			get
			{
				return this._enduser;
			}
			set
			{
				if ((this._enduser != value))
				{
					this.OnenduserChanging(value);
					this.SendPropertyChanging();
					this._enduser = value;
					this.SendPropertyChanged("enduser");
					this.OnenduserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
