<?xml version="1.0" encoding="utf-8"?><Database Name="Luckynumber" Class="LinqtoSQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=HAN-L-3PFF7H2;Initial Catalog=Luckynumber;Persist Security Info=True;User ID=sa" SettingsObjectName="arconfirmationletter.Properties.Settings" SettingsPropertyName="LuckynumberConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_dacbiet" Member="tbl_dacbiets">
    <Type Name="tbl_dacbiet">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="luckynumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="luckydate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Temp" Member="tbl_Temps">
    <Type Name="tbl_Temp">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Version" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="server" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="signoffby" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="possition" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="phonecontact" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="siteid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="note" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="contactperson" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="nameofbarnch" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="addressofbarnch" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="DeleteData" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EditServerData" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Depositintput" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EditReportsaffter" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="InputDepositInpass" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PriodMake" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Systemconfig" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="uploadBeginbalance" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="endyearPackdata" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="makedepostfromadjamount" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="deductdepositamount" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="redoInputviry" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="uploadpriviousPriod" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="imagesign" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="nationKA" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>