<?xml version="1.0" encoding="utf-8"?><Database Name="Luckynumber" Class="LinqtoSQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=HAN-L-3PFF7H2;Initial Catalog=Luckynumber;Persist Security Info=True;User ID=sa" SettingsObjectName="Luckynumber.Properties.Settings" SettingsPropertyName="LuckynumberConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_ChecktongKM" Member="tbl_ChecktongKMs">
    <Type Name="tbl_ChecktongKM">
      <Column Name="Sold_to_party" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="enduser" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="maCTKM" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Ma_SP_Duoc_KM" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="So_luong_duoc_KM" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="So_luong_thuc_te_KM" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PO_message" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Sale_Region" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="So_luong_hang_Mua" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="STT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenCTKM" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Temp" Member="tbl_Temps">
    <Type Name="tbl_Temp">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Version" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="server" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="enduser" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="signoffby" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="possition" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="phonecontact" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="siteid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="note" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="contactperson" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="nameofbarnch" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="addressofbarnch" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="DeleteData" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EditServerData" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Depositintput" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EditReportsaffter" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="InputDepositInpass" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PriodMake" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Systemconfig" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="uploadBeginbalance" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="endyearPackdata" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="makedepostfromadjamount" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="deductdepositamount" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="redoInputviry" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="uploadpriviousPriod" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="imagesign" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="nationKA" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_CTKM" Member="tbl_CTKMs">
    <Type Name="tbl_CTKM">
      <Column Name="[Mã CT]" Member="Mã_CT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[PO Message]" Member="PO_Message" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Mã SP Mua]" Member="Mã_SP_Mua" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Mã SP KM]" Member="Mã_SP_KM" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Tên SP mua]" Member="Tên_SP_mua" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Tên SP KM]" Member="Tên_SP_KM" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Tỷ lệ CTKM]" Member="Tỷ_lệ_CTKM" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Từ ngày]" Member="Từ_ngày" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Đến Ngày]" Member="Đến_Ngày" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Nhóm khách hàng]" Member="Nhóm_khách_hàng" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="enduser" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_NhomKHKM" Member="tbl_NhomKHKMs">
    <Type Name="tbl_NhomKHKM">
      <Column Name="Mã_nhóm_KH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="CodeKH" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="enduser" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Product" Member="tbl_Products">
    <Type Name="tbl_Product">
      <Column Name="[Marterial code]" Member="Marterial_code" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Marterial name]" Member="Marterial_name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Pack size]" Member="Pack_size" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[PC Quy chuan]" Member="PC_Quy_chuan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[UC Rate]" Member="UC_Rate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="enduser" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_SalesFreehavetopaid" Member="tbl_SalesFreehavetopaids">
    <Type Name="tbl_SalesFreehavetopaid">
      <Column Name="Order_Number" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ma_CTKM" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Material" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EstimateFree_quantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="enduser" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_SalesFreeOrder" Member="tbl_SalesFreeOrders">
    <Type Name="tbl_SalesFreeOrder">
      <Column Name="Created" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Dlv_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SOrg" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PO_number" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ma_CTKM" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="New_PO_number" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Order_Number" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Material" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Sold_to_party" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Doc_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Order_quantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ConfirmQty" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Item" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Net_price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Rj" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Plnt" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Net_value" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="byOrder" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rptselect" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="enduser" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Salesorder" Member="tbl_Salesorders">
    <Type Name="tbl_Salesorder">
      <Column Name="Created" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SOrg" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PO_number" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Doc_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Dlv_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Order_Number" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Sold_to_party" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Material" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Order_quantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ConfirmQty" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Item" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Net_price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Rj" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Plnt" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Net_value" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="selectprt" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="enduser" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="maCTKM" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Ma_SP_Duoc_KM" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="So_luong_duoc_KM" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Mã_nhóm_KH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
</Database>